'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),crypto=require('node:crypto');
const {createReviewServer,validate}=require('../tools/review-server.cjs'),{createSimulator,ROOT}=require('../tools/runtime.cjs'),{summary}=require('../tools/frame-export.cjs'),Binary=require('../tools/binary-frame.cjs');
async function main(){
 const output=path.join(ROOT,'outputs','review-demo-test-'+Date.now()),app=createReviewServer({port:0,outputRoot:output}),address=await app.listen(),base='http://127.0.0.1:'+address.port,rows=[];
 const request={scene:'construction_v1',generator:'range',seed:73017,pose:'auto',mode:'frame',time:3,fps:1,controls:{radialSigma:.06},edgeMixing:false};
 const post=async(body,headers={})=>fetch(base+'/api/jobs',{method:'POST',headers:{'Content-Type':'application/json','X-Lidar-Review':'1',...headers},body:JSON.stringify(body)});
 async function wait(id){for(let n=0;n<1200;n++){const j=await(await fetch(base+'/api/jobs/'+id)).json();if(j.status!=='running'){assert.equal(j.status,'complete',j.error);return j;}await new Promise(r=>setTimeout(r,250));}throw Error('Job timeout');}
 async function run(body){const res=await post(body);assert.equal(res.status,202);const started=await res.json(),job=await wait(started.id);assert(job.frames.length>0);const frame=Binary.read(path.join(output,job.id,'0000.lsf.gz'));assert(frame.arrays.xyz.every(Number.isFinite));assert.equal(frame.metadata.routePreview.length,101);assert.equal(frame.metadata.field_calibrated,false);assert.equal(frame.metadata.training_approved,false);assert.deepEqual(frame.metadata.routePreview[Math.round(body.time*10)].world,frame.metadata.sensorPose.world);rows.push({scene:body.scene,generator:body.generator,frames:job.frames.length,points:frame.metadata.points,noise:frame.metadata.stats.dust,hash:frame.metadata.xyz_labels_sha256,elapsedS:job.elapsedS});console.log('PASS '+body.scene+' '+body.generator+' '+job.frames.length+' frames');return {job,frame};}
 try{
  const catalog=await(await fetch(base+'/api/catalog')).json();assert.equal(catalog.scenes.length,24);assert.equal(catalog.generators.length,8);assert(catalog.scenes.every(s=>s.poses.length===40));
  assert.equal((await fetch(base+'/')).status,200);
  for(const bad of [{...request,seed:-1},{...request,pose:40},{...request,scene:'room_v1',generator:'rain'},{...request,controls:{radialSigma:.2}},{...request,fps:100}])assert.equal((await post(bad)).status,400);
  assert.equal((await post(request,{'Origin':'http://example.com'})).status,403);
  assert.equal((await fetch(base+'/api/jobs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(request)})).status,403);
  for(const s of catalog.scenes)await run({...request,scene:s.id});
  let dust;
  for(const g of catalog.generators.filter(g=>g.id!=='range')){const result=await run({...request,generator:g.id});if(g.id==='dust')dust=result;}
  const direct=createSimulator();try{const f=await direct.run({...validate({...request,generator:'dust'},{scenes:catalog.scenes}).options,time:3});assert.equal(summary(f).xyz_labels_sha256,dust.frame.metadata.xyz_labels_sha256);assert.deepEqual(f.result.xyz,dust.frame.arrays.xyz);}finally{direct.close();}
  const context={window:{},fetch,Response,Blob,DecompressionStream,TextDecoder,atob,crypto:crypto.webcrypto,Uint8Array,Uint32Array,Float32Array,Float64Array,DataView,Map,setTimeout};vm.createContext(context);vm.runInContext(fs.readFileSync(path.join(ROOT,'src/review_demo_viewer.js'),'utf8'),context);const browserRead=await context.window.ReviewDisplay.readFrame(base+dust.job.frames[0].url);assert.deepEqual(browserRead.arrays.xyz,dust.frame.arrays.xyz);assert.equal(browserRead.metadata.xyz_labels_sha256,dust.frame.metadata.xyz_labels_sha256);
  const repeated=await run({...request,generator:'dust'});assert.equal(repeated.frame.metadata.xyz_labels_sha256,dust.frame.metadata.xyz_labels_sha256);
  const changed=await run({...request,generator:'dust',seed:73117});assert.notEqual(changed.frame.metadata.xyz_labels_sha256,dust.frame.metadata.xyz_labels_sha256);assert.notDeepEqual(changed.frame.metadata.sequencePlan.dustSource,dust.frame.metadata.sequencePlan.dustSource);
  const seq=await run({...request,mode:'sequence',time:0});assert.equal(seq.job.frames.length,11);assert.deepEqual(seq.job.frames.map(f=>f.time),Array.from({length:11},(_,i)=>i));const last=Binary.read(path.join(output,seq.job.id,'0010.lsf.gz'));assert.notDeepEqual(seq.frame.metadata.sensorPose.world,last.metadata.sensorPose.world);assert.deepEqual(seq.frame.metadata.routePreview,last.metadata.routePreview);const manifest=await(await fetch(base+seq.job.manifestUrl)).json();assert.equal(manifest.frames.length,11);assert.equal(manifest.fieldCalibrated,false);
  const pending=await(await post({...request,generator:'rain',mode:'sequence'})).json();assert.equal((await post(request)).status,409);const cancel=await fetch(base+'/api/jobs/'+pending.id+'/cancel',{method:'POST',headers:{'X-Lidar-Review':'1'}});assert.equal((await cancel.json()).status,'cancelled');await new Promise(r=>setTimeout(r,200));assert.equal((await(await fetch(base+'/api/catalog')).json()).active,null);
  const report={passed:true,created:new Date().toISOString(),scenes:24,generators:8,rows,apiGuards:true,cancellation:true,browserBinaryExact:true,directRuntimeExact:true,sequenceFrames:11,outputRoot:path.relative(ROOT,output),fieldCalibrated:false,trainingApproved:false};fs.writeFileSync(path.join(output,'validation.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({passed:true,report:path.join(output,'validation.json')}));
 }finally{app.server.close();app.server.closeAllConnections();}
}
main().catch(e=>{console.error(e);process.exitCode=1;});
