(async function(){
'use strict';
const $=id=>document.getElementById(id),D=ReviewDisplay,index=await fetch('assets/noise_lab_v1/index.json').then(r=>r.json()),thumb=new D.ReviewViewer($('thumb-host')),viewer=new D.ReviewViewer($('viewer')),images=new Map();let report,page=0,ticket=0,detailTicket=0,previewQueue=Promise.resolve(),detailQueue=Promise.resolve();
const row=scene=>({...index.scenes.find(s=>s.id===scene),geometry:index.geometry_knobs_v3.scenes.find(s=>s.scene===scene),poses:index.sensor_positions_v19.scenes[scene].positions});
const fail=e=>{$('error').textContent=String(e.stack||e);};
function tabs(detail){$('gallery').hidden=detail;$('detail').hidden=!detail;if(detail)requestAnimationFrame(()=>viewer.resize());}
async function refresh(){report=await fetch('audit/manifest.json').then(r=>r.json());const complete=report.cases.filter(r=>r.passed).length;$('progress').textContent=complete+'/100조건 · '+report.cases.reduce((a,r)=>a+r.frames.length,0)+'프레임 · '+report.errors.length+'오류'+(report.complete?' · 생성 완료':' · 생성 중');const dust=report.cases.filter(c=>c.passed&&c.generator==='dust'),empty=dust.filter(c=>c.frames.every(f=>f.labels[1]===0));$('dust-summary').textContent='완료된 먼지 '+dust.length+'조건 중 '+empty.length+'조건은 10초 전체에서 먼지 반환이 0개입니다. 입자가 없다는 뜻이 아니며 시야·가림·신호 경쟁을 함께 봐야 합니다. 밀도를 사후 조작하지 않았습니다.';const old=$('case').value;$('case').replaceChildren();for(const c of report.cases.filter(r=>r.frames.length)){const o=new Option(c.id+' '+c.options.scene+' '+c.generator,c.id);$('case').add(o);}if(old)$('case').value=old;await gallery();}
async function preview(c){
 const job=previewQueue.then(()=>makePreview(c));previewQueue=job.catch(()=>{});return job;
}
async function makePreview(c){
 if(images.has(c.id))return images.get(c.id);const f=c.frames.find(f=>f.time===5);if(!f)return null;
 const data=await D.readFrame('audit/'+f.file);await thumb.setScene(row(c.options.scene));thumb.setFrame(data);thumb.az=-1.15;thumb.el=.78;thumb.setOptions({display:'combined',color:'labels',cutaway:D.indoor(row(c.options.scene)),particles:false,poses:false,noise:false,size:2,path:true});thumb.fitScene();thumb.render();const context=thumb.renderer.domElement.toDataURL('image/png');
 thumb.setOptions({display:'points',cutaway:false});thumb.fitRoute();thumb.render();const local=thumb.renderer.domElement.toDataURL('image/png');const value={context,local,hash:data.metadata.xyz_labels_sha256};images.set(c.id,value);return value;
}
async function gallery(){const id=++ticket;$('error').textContent='';$('grid').dataset.ready='loading';$('gallery-status').textContent='실제 좌표 렌더 중';$('grid').replaceChildren();$('previous').disabled=page===0;$('next').disabled=page===9;$('page').value=page;
 for(const c of report.cases.slice(page*10,page*10+10)){
  if(id!==ticket)return;const a=document.createElement('article'),img=document.createElement('img'),p=document.createElement('p'),t=document.createElement('strong');t.textContent=c.id+' · '+c.options.scene+' · '+c.generator+(Number(c.id)>=97?' · 경계 검사':'');p.append(t);const f=c.frames.find(f=>f.time===5);p.append(document.createElement('br'),document.createTextNode(c.options.sensor+' · '+(f?f.points.toLocaleString()+'점 / 산란·가짜 '+f.labels[1]+' / 불확실 '+f.labels[2]:'계산 중')));if(Number(c.id)>=97)p.append(document.createElement('br'),document.createTextNode({'097':'비20mm/h','098':'눈 농도10','099':'안개 시정50m (기본500m)','100':'기본 거리오차 끔'}[c.id]));img.alt=c.id+' '+c.options.scene+' '+c.generator+' 실제 저장 관측';a.append(img,p);$('grid').append(a);
  const value=await preview(c);if(id!==ticket)return;if(value){img.src=value[$('angle').value];img.dataset.hash=value.hash;img.onclick=()=>void open(c.id,5).catch(fail);}if(c.error)a.classList.add('error');
 }
 $('gallery-status').textContent=(page*10+1)+'~'+Math.min(page*10+10,report.cases.length)+' · 실제 좌표 렌더 완료';$('grid').dataset.ready=String(page);$('grid').dataset.angle=$('angle').value;
}
async function open(id,time=5){const t=++detailTicket,job=detailQueue.then(()=>openDetail(id,time,t));detailQueue=job.catch(()=>{});return job;}
async function openDetail(id,time,t){if(t!==detailTicket)return;const changed=viewer.caseId!==id,c=report.cases.find(c=>c.id===id);if(!c)return;const f=c.frames.find(f=>f.time===Number(time))||c.frames.at(-1);if(!f)return;time=f.time;$('time').max=c.frames.at(-1).time;tabs(true);$('case').value=id;$('time').value=time;$('time-label').textContent=time+'초';$('case-info').textContent=c.options.scene+' · '+c.generator+' · '+c.options.sensor+' · 환경 시드 '+c.options.seed+' · 기기 '+c.options.beamUnit.seed;
 $('viewer-caption').textContent='저장 프레임 읽는 중';const frame=await D.readFrame('audit/'+f.file);if(t!==detailTicket)return;if(viewer.row?.id!==c.options.scene)await viewer.setScene(row(c.options.scene));if(t!==detailTicket)return;viewer.setFrame(frame);viewer.setOptions({color:$('color').value,particles:$('particles').checked,cutaway:$('cutaway').checked});if(changed)viewer.fitRoute();viewer.caseId=id;$('viewer-caption').textContent=c.id+' · '+time+'초 · '+f.points+'점 · 해시 확인';$('metadata').textContent=JSON.stringify({route:c.route,noiseRangeBins:f.noiseRangeBins,pose:frame.metadata.sensorPose,settings:c.options,hash:f.hash},null,2);
}
for(let i=0;i<10;i++)$('page').add(new Option((i*10+1)+'~'+(i*10+10),i));
$('page').onchange=()=>{page=+$('page').value;void gallery().catch(fail);};$('angle').onchange=()=>void gallery().catch(fail);$('previous').onclick=()=>{page=Math.max(0,page-1);void gallery().catch(fail);};$('next').onclick=()=>{page=Math.min(9,page+1);void gallery().catch(fail);};$('refresh').onclick=()=>void refresh().catch(fail);$('gallery-tab').onclick=()=>tabs(false);$('detail-tab').onclick=()=>void open($('case').value).catch(fail);$('case').onchange=()=>void open($('case').value,5).catch(fail);$('time').oninput=()=>void open($('case').value,$('time').value).catch(fail);$('fit-scene').onclick=()=>viewer.fitScene();$('fit-route').onclick=()=>viewer.fitRoute();$('fit-source').onclick=()=>viewer.fitSource();for(const k of ['color','particles','cutaway'])$(k).onchange=()=>viewer.setOptions({color:$('color').value,particles:$('particles').checked,cutaway:$('cutaway').checked});
await refresh();
})().catch(e=>{document.getElementById('error').textContent=String(e.stack||e);});
