__RANDOM__
__JOBS_V13__
const $=id=>document.getElementById(id),D=JSON.parse($('lab-index').textContent),embedded=JSON.parse($('lab-embedded').textContent),fmt=n=>n.toLocaleString('ko-KR');
const cache=new Map(),coreURL=URL.createObjectURL(new Blob([$('three-runtime').textContent,$('lab-worker').textContent],{type:'text/javascript'}));
const worker=new LatestTaskWorker(coreURL,handleSimulation,e=>viewFailure('신호 계산',e),600000);
worker.onProgress=p=>{$('sim-overlay').textContent='연속 입자와 광선 계산 '+Math.round(p*100)+'% · 128채널 강수는 수 분 걸릴 수 있습니다.';};
let category='dust',realData=null,simData=null,result=null,job=0,realTicket=0,simTicket=0,latestConfig=null;
const shared={az:.6,el:.45,radius:14};
function pane(id){const host=$(id),scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(52,1,.01,20000),renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setClearColor(0x0c1721);host.prepend(renderer.domElement);camera.up.set(0,0,1);const p={host,scene,camera,renderer,target:new THREE.Vector3(),xyz:null,labels:null,clouds:[]};p.resize=()=>{const w=host.clientWidth,h=host.clientHeight;if(w<1||h<1)return false;if(p.width!==w||p.height!==h){renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();p.width=w;p.height=h;}return true;};new ResizeObserver(()=>{if(p.resize())draw()}).observe(host);renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();p.contextLost=true;host.dataset.context='lost';viewFailure('3D 표시',new Error('그래픽 연결이 끊겼습니다. 복구를 기다린 뒤 다시 표시해 주세요'));});renderer.domElement.addEventListener('webglcontextrestored',()=>{p.contextLost=false;host.dataset.context='ready';requestAnimationFrame(()=>{draw();loadScene();});});let drag=null;host.oncontextmenu=e=>e.preventDefault();host.onpointerdown=e=>{drag={x:e.clientX,y:e.clientY,button:e.button};host.setPointerCapture(e.pointerId)};host.onpointerup=()=>drag=null;host.onpointercancel=()=>drag=null;host.onpointermove=e=>{if(!drag)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;drag.x=e.clientX;drag.y=e.clientY;if(drag.button===2){const right=new THREE.Vector3().setFromMatrixColumn(camera.matrixWorld,0),up=new THREE.Vector3().setFromMatrixColumn(camera.matrixWorld,1);p.target.addScaledVector(right,-dx*shared.radius/host.clientHeight).addScaledVector(up,dy*shared.radius/host.clientHeight)}else{shared.az-=dx*.007;shared.el=Math.max(-1.4,Math.min(1.5,shared.el+dy*.007))}draw()};host.addEventListener('wheel',e=>{e.preventDefault();shared.radius=Math.max(.3,Math.min(2000,shared.radius*Math.exp(e.deltaY*.001)));draw()},{passive:false});return p}
const left=pane('real-view'),right=pane('sim-view'),panes=[left,right];
function draw(){if(typeof panes==='undefined')return;for(const p of panes){if(p.contextLost||!p.resize())continue;const t=p.target,r=shared.radius;p.camera.position.set(t.x+r*Math.cos(shared.el)*Math.cos(shared.az),t.y+r*Math.cos(shared.el)*Math.sin(shared.az),t.z+r*Math.sin(shared.el));p.camera.lookAt(t);p.renderer.render(p.scene,p.camera);p.host.dataset.drawCount=String((+p.host.dataset.drawCount||0)+1);p.host.dataset.renderedPoints=String(p.clouds.filter(o=>o.visible).reduce((n,o)=>n+o.geometry.attributes.position.count,0));}}
function cloud(p,xyz,labels,reflectivity){for(const o of p.clouds){p.scene.remove(o);o.geometry.dispose();o.material.dispose()}p.clouds=[];p.xyz=xyz;p.labels=labels;for(let type=0;type<3;type++){const x=[],colors=[];for(let i=0;i<labels.length;i++)if(labels[i]===type){x.push(xyz[i*3],xyz[i*3+1],xyz[i*3+2]);const v=reflectivity?.[i],q=Number.isFinite(v)?Math.sqrt(Math.max(0,Math.min(1,v/.7))):.4;colors.push(q,q,q);}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(x,3));g.setAttribute('color',new THREE.Float32BufferAttribute(colors,3));const m=new THREE.PointsMaterial({color:[0x91b9c4,0xff875d,0xe8c56a][type],size:2.2,sizeAttenuation:false});const o=new THREE.Points(g,m);o.userData.type=type;p.scene.add(o);p.clouds.push(o)}colors()}
function colors(){right.host.dataset.colorMode=$('show-reflectivity').checked?'reflectivity':$('show-labels').checked?'labels':'plain';for(const p of panes)for(const o of p.clouds){const t=o.userData.type;o.material.vertexColors=p===right&&$('show-reflectivity').checked;o.material.needsUpdate=true;o.material.color.set(o.material.vertexColors?0xffffff:$('show-labels').checked?[0x91b9c4,0xff875d,0xe8c56a][t]:0xb3cad1);o.visible=t>0||!$('noise-only').checked||(p===left&&!p.labels.some(v=>v>0))}draw()}
function focus(full=false){let rad=8;for(const p of panes){if(!p.xyz?.length){p.target.set(0,0,1);continue}const ids=[];for(let i=0;i<p.labels.length;i++)if(full||p.labels[i]===1)ids.push(i);if(!ids.length)for(let i=0;i<p.labels.length;i++)ids.push(i);const sums=[0,0,0];for(const i of ids)for(let k=0;k<3;k++)sums[k]+=p.xyz[i*3+k]/ids.length;p.target.fromArray(sums);let extent=0;for(const i of ids){const dx=p.xyz[i*3]-sums[0],dy=p.xyz[i*3+1]-sums[1],dz=p.xyz[i*3+2]-sums[2];extent=Math.max(extent,Math.sqrt(dx*dx+dy*dy+dz*dz))}rad=Math.max(rad,Math.min(full?500:150,extent*(full?1.35:2)))}if(usesBeforeView()){if(full)right.target.copy(left.target);else left.target.copy(right.target);}shared.radius=rad;draw()}
function decode(s,T){const b=Uint8Array.from(atob(s),c=>c.charCodeAt(0));return new T(b.buffer)}
async function data(id){if(cache.has(id))return cache.get(id);const d=embedded[id]||await fetch('assets/noise_lab_v1/'+id+'.json').then(r=>{if(!r.ok)throw Error('자료 HTTP '+r.status);return r.json()});cache.set(id,d);return d}
function activeCategory(){return ['dust','range','rain','snow','fog','sun'].includes(category)||(category==='general'&&$('general-mode').value!=='none')}
function outdoor(){return /^(construction|crane_yard|apartment)_/.test($('sim-scene').value)}
function cfg(){const base={sceneLayout:simData?.scanGeometry?.sceneLayout||null,edgeMixing:$('edge-mixing').checked,dustShapeKey:simData?.id||$('sim-scene').value,...motionConfig(),...solarConfig(),weather:['dust','rain','snow','fog'].includes(category)?category:'none',weatherEnabled:$('weather-enabled').checked&&(category==='dust'||category==='fog'||outdoor()),weatherConcentration:+$('weatherConcentration').value,weatherDiameter:+$('weatherDiameter').value,weatherReturn:+$('weatherReturn').value,weatherAlpha:+$('weatherAlpha').value,seed:+$('seed').value>>>0,time:$('sequence-enabled').checked?+$('sequence-time').value:motionActive()?+$('motion-time').value:+$('time').value,extinction:+$('extinction').value,wind:+$('wind').value,diffusion:+$('diffusion').value,settling:+$('settling').value,emitterX:+$('motionX').value,emitterY:+$('motionY').value,radialSigma:activeCategory()&&$('range-enabled').checked?+$('radialSigma').value:0,radialSlope:activeCategory()&&$('range-enabled').checked?+$('radialSlope').value/1000:0,surfaceModel:activeCategory()&&$('surface-response').checked&&$('scan-mode').value!=='ideal',dust:false,...atmosphereConfig(),...fullRangeConfig()};return sequenceConfig(NoiseLabParameters.apply(base,D.parameter_distributions_v18,$('sim-scene').value,$('weather-jitter').checked))}
function generate(){if(!simData||simData.id!==$('sim-scene').value)return;worker.cancel();++job;viewBusy('선택한 조건을 계산하고 있습니다.');syncGeometryRandom();weatherControls();if(simData.scanProfile==='live'&&simData.geometryKey!==geometryKey()){requestGeometry();return;}const config=cfg();for(const k of ['time','extinction','wind','diffusion','settling','radialSigma'])$(k+'-out').textContent=config[k];$('radialSlope-out').textContent=(config.radialSlope*1000).toFixed(1);latestConfig=config;const id=++job;$('sim-view').dataset.ready='false';$('sim-overlay').textContent='광선과 반환 신호 계산 중…';worker.run({id,input:simData.scanInput||{sensor:simData.sensor,ranges:simData.rangesArray},config,raw:simData.liveRaw,beam:simData.liveBeam,terrainCm:geometryConfig().terrainCm})}
function handleSimulation(e){if(e.data.id!==job)return;if(e.data.error){viewFailure('신호 계산',e.data.error);return}result=e.data.result;for(const key of ['backgroundSource','backgroundRangeRms','dustFlux','dustDisplayFraction','dustShapeSeed','dustSourceProfile','reviewKind','reviewEnabled','version','uncertain','motionModel','particles','worldPoints','backgroundPoints','time','view','weather','weatherAlpha','weatherEnabled','weatherIntersections','temporalCoherence','receiverMode','patternLegacy','fullRange','rangeSupport','rangeBins','candidateBins'])delete right.host.dataset[key];renderSimulation();const s=result.stats,active=activeCategory();$('sim-overlay').textContent=category==='dust'?'새 먼지 '+fmt(s.dust)+'점 · 시드 '+result.config.seed:category==='range'?'광선 방향 거리 오차 · σ '+result.config.radialSigma+'m':'해당 원인 생성 0점 · 장소만 표시';$('sim-info').textContent=category==='dust'?'물체 유지 '+fmt(s.surface)+'점 / 먼지로 대체 '+fmt(s.replaced)+'점 / 검출 누락 '+fmt(s.lost)+'점 / 빈 방향의 먼지 '+fmt(s.skyDust)+'점. 풍속·감쇠·반사율은 미교정 가정.':category==='range'?'실제 표면만 흔들었습니다. 제거 정답 0점. 실측 오차와의 짝 비교가 없어 σ의 현실성은 미검증.':'생성 미지원. 실측 자료만 검토하고, 이 원인은 합성·학습에 포함하지 않습니다.';Object.assign($('sim-view').dataset,{ready:'true',category,scene:simData.id,seed:String(result.config.seed),noise:String(s.dust),surface:String(s.surface),lost:String(s.lost),replaced:String(s.replaced),unsupportedZero:String(active||s.dust===0),training:'false',rangeEnabled:String(s.rangeError.enabled),radialSigma:String(result.config.radialSigma),radialSlope:String(result.config.radialSlope),surfaceRangeRms:String(s.rangeError.surface.rms),dustRangeRms:String(s.rangeError.dust.rms),scanProfile:simData.scanProfile||'ideal',terrainCm:String(simData.scanGeometry?.config?.terrainCm??''),pitchDeg:String(simData.scanGeometry?.config?.pitchDeg??''),rollDeg:String(simData.scanGeometry?.config?.rollDeg??''),wobbleDeg:String(simData.scanGeometry?.config?.wobbleDeg??''),opticalOffset:String(simData.scanGeometry?.config?.opticalOffset??''),geometryCastMs:String(simData.scanGeometry?.castMs??''),rays:String(s.rays),surfaceModel:String(result.config.surfaceModel??false)});weatherSummary();solarSummary();atmosphereSummary();rangePanel();featureCards();availabilitySummary();fullRangeSummary();right.host.dataset.uiRevision='24';channelSummary();sensorPoseSummary();observationSummary();if(!$('sim-view').dataset.focused){focus();$('sim-view').dataset.focused='true'}motionAfterResult();simpleUI();right.host.dataset.ready='true';right.host.dataset.displayScene=simData.id;right.host.dataset.displayCategory=category;right.host.dataset.displayState='current';$('view-status').textContent='표시 완료 · '+$('sim-scene').selectedOptions[0].textContent;$('view-retry').hidden=true;draw();sequenceAfterResult();}
async function loadScene(){cancelViewWork();const t=++simTicket,id=$('sim-scene').value,profile=$('scan-mode').value;simData=null;result=null;viewBusy('새 장소를 불러오고 있습니다.');try{const d={...await data(id)};if(t!==simTicket)return;if(lastKnobScene!==d.id){if($('geometry-random').checked)resetGeometryKnobs(d.id);lastKnobScene=d.id;}d.rangesArray=decode(d.ranges,Float32Array);await prepareScan(d,profile);if(t!==simTicket)return;simData=d;right.host.dataset.focused='';scanSummary();generate()}catch(e){if(t===simTicket)viewFailure('장소 불러오기',e)}}
async function loadReal(){const t=++realTicket,id=$('real-sample').value;if(usesBeforeView()){beforeView();featureCards();return;}$('real-title').textContent='실측 표본 · 원본 라벨';if(!id){realData=null;cloud(left,new Float32Array(),new Uint8Array());$('real-overlay').textContent='대응 실측 없음';$('real-info').textContent='이 원인을 식별·교정할 실측 자료를 아직 확보하지 못했습니다.';Object.assign(left.host.dataset,{sample:'none',points:'0',noise:'0',category});featureCards();return}try{const d=await data(id);if(t!==realTicket)return;realData=d;d.xyzArray=decode(d.xyz,Float32Array);d.labelsArray=decode(d.labels,Uint8Array);cloud(left,d.xyzArray,d.labelsArray);const positives=d.labelsArray.filter(v=>v===1).length,candidates=d.labelsArray.filter(v=>v===2).length;$('real-overlay').textContent=d.meta.dataset+' · 표시 '+fmt(d.n)+'점'+(positives?' / 대상 '+fmt(positives)+'점':candidates?' / 미검증 후보 '+candidates+'점':'');$('real-info').textContent=d.meta.label_status+' · '+d.meta.note;Object.assign(left.host.dataset,{sample:id,points:String(d.n),noise:String(positives),category:d.meta.category});featureCards();focus()}catch(e){$('real-info').textContent=String(e)}}
function changeCategory(){cancelViewWork();realData=null;category=$('category').value;weatherPreset();const changedScene=ensureWeatherScene();++job;result=null;right.host.dataset.ready='false';right.host.dataset.focused='';viewBusy('새 종류로 전환하고 있습니다.');const rr=D.real.filter(r=>r.category===category);$('real-sample').replaceChildren(...rr.map(r=>new Option(r.title+(['rain','snow'].includes(r.category)?' · 점별 오류 라벨 없음':' · '+(r.noise||0)+' 대상점'),r.id)));if(category==='dust'){const sample=[...rr].filter(r=>r.noise>=17).sort((a,b)=>Math.abs(a.noise/a.n-.05)-Math.abs(b.noise/b.n-.05))[0];if(sample)$('real-sample').value=sample.id}if(!rr.length)$('real-sample').add(new Option('대응 실측 미확보',''));$('real-sample').disabled=!rr.length;const active=activeCategory();$('generator-controls').disabled=false;$('new-seed').disabled=false;$('surface-response').disabled=!active||$('scan-mode').value==='ideal';for(const k of ['extinction','wind','diffusion','settling','time','advance','emitterX','emitterY'])$(k).disabled=true;$('noise-only').checked=false;const hasLabels=['rain','snow'].includes(category)||rr.some(r=>r.noise>0||r.category==='spray');$('noise-only').disabled=!hasLabels;$('generated-title').textContent=category==='dust'?'먼지 생성 후보':category==='range'?'거리 흔들림 가정':'이 원인은 생성하지 않음';$('mode-note').textContent=category==='general'?'항공 확대 표본의 둥근 외곽은 반경 30m 표시 경계입니다. 주황은 제공자의 Class 7일 뿐, 확정 노이즈·삭제 정답이 아닙니다. 나머지 관측도 정상임을 보장하지 않습니다.':category==='dust'?'실측과 합성은 서로 다른 장소입니다. 같은 확대율로 비교하지만, 같은 장면의 전후 비교나 실측 교정 결과는 아닙니다.':category==='reflection'?'유리·거울 관측은 보존합니다. 재질 표면과 반사 허상을 한꺼번에 제거하지 않습니다.':category==='range'?'거리 흔들림은 실제 표면을 유지하는 오차입니다. 실측과의 짝 비교가 없어 왼쪽은 비워 둡니다.':'생성 근거가 부족해 현재 생성 점 수는 0입니다. 이는 현실에 이 현상이 없다는 뜻이 아닙니다.';setGeometryEnabled();weatherControls();simpleUI();loadReal();if(changedScene)loadScene();else generate()}
function featureCards(){if(category==='range'){rangeFeaturesV9();return;}if(atmosphereActive()){atmosphereFeatures();return;}if(category==='sun'){solarFeatures();return;}if(motionActive()){motionFeatures();return;}if(['rain','snow','fog'].includes(category)){weatherFeatures();return;}if(category!=='dust'){const explanations={rain:'빗방울과 젖은 실제 표면을 점별로 구분할 정답이 없음',snow:'낙하 눈과 눈 덮인 지면을 구분할 확보 라벨이 없음',spray:'변환본 색상과 원래 점 라벨의 대응이 미검증',general:'제공자의 Class 7만 보존했습니다. 개별 점의 오분류 가능성과 발생 원인은 미검증이므로 생성·삭제 정답에서 제외합니다.',reflection:'재질 표면과 허상의 제거 정책을 사용자가 정할 때까지 보존',sun:'공식 실측 배포 링크가 403, 센서별 배경광 교정값 미확보',fog:'대응 실측과 센서별 감쇠·검출 교정값 미확보',range:'실측 오차의 짝 자료 없이 σ를 가정한 빔 방향 흔들림'};const meta=realData?.meta;const count=meta?.source_noise;$('features').innerHTML='<div class="card"><h3>확보된 관측</h3><p>'+(realData?fmt(realData.n)+'개 표시점 · '+meta.label_status:'대응 실측 미확보')+'</p>'+(count===undefined?'':'<p>전체 원본 타일 Class 7 '+fmt(count)+' / '+fmt(meta.source_points)+'점</p>')+'</div><div class="card"><h3>특징 해석의 범위</h3><p>'+explanations[category]+'</p></div><div class="card"><h3>현재 생성 정책</h3><p>'+(category==='range'?'표면을 흔들되 제거 정답 0점':'이 원인 생성 0점')+'</p><p class="muted">다른 종류의 가짜점으로 대체하지 않습니다.</p></div>';$('feature-note').textContent='라벨 부재와 노이즈 부재는 다릅니다. 관측 전체 또는 표면을 오류로 간주하지 않습니다.';return}if(!result){$('features').replaceChildren();$('feature-note').textContent='';return}const source=realData?.meta.dataset==='Ouster'?'Ouster':'UCHILE',bands=D.features[source],m=result.metrics,rm=realData?.meta.metrics;const specs=[['전체 관측 중 먼지',m.fraction,rm?.dust_fraction,bands.dust_fraction],['먼지의 짧은 축 / 긴 축',m.thickness,rm?.global_axis_ratio?.[0],bands.global_thickness_ratio],['물체 중앙값만큼 조밀한 먼지',m.denseFraction,rm?.dust_no_sparser_than_real_median,bands.dust_no_sparser_than_real_median]];$('features').innerHTML=specs.map(([name,v,r,b])=>{const num=x=>x==null?'계산 불가':(100*x).toFixed(1)+'%',inside=v!==null&&v>=b[0]&&v<=b[2];return '<div class="card"><h3>'+name+'</h3><p>실측 예시 '+num(r)+' · <strong>생성 '+num(v)+'</strong></p><div class="meter"><span class="band" style="left:'+b[0]*100+'%;width:'+(b[2]-b[0])*100+'%"></span>'+(v===null?'':'<span class="pin" style="left:'+Math.min(99.5,100*v)+'%"></span>')+'</div><div class="result">'+source+' 교정 프레임 10~90% 범위 '+num(b[0])+'~'+num(b[2])+'<br>'+(v===null?'17점 미만으로 형태 비교 제외':inside?'범위 안, 재현 검증을 뜻하지 않음':'범위 밖, 차이를 검토하세요')+'</div></div>'}).join('');$('mode-note').textContent='실측과 합성은 서로 다른 장소·센서 조건입니다. '+(m.denseFraction!==null&&(m.denseFraction<bands.dust_no_sparser_than_real_median[0]||m.denseFraction>bands.dust_no_sparser_than_real_median[2])?'현재 후보의 상대 밀도는 실측 교정 범위 밖입니다. 수정·검토가 필요합니다.':'일부 특징이 범위에 들어가도 실측 재현이 검증된 것은 아닙니다.');$('feature-note').textContent='밀도 지표는 생성쪽 최대 128점, 실측 예시는 기존 최대 1,536점 표본의 8-최근접 거리로 계산합니다. 원본 점 수와 광선 분포가 달라 정밀한 동등성 검정은 아닙니다. 배경·신호 강도·풍속은 교정하지 않았습니다.'}
function sourceRows(){const filter=$('source-filter').value;const rows=D.registry.filter(r=>filter==='all'||r.category===filter||(filter==='weather'&&/rain|snow|fog|spray|sun|weather|synthetic/.test(r.category)));$('source-count').textContent=rows.length+' / '+D.registry.length+'개 출처';$('source-rows').innerHTML=rows.map(r=>'<tr><td><a target="_blank" rel="noopener" href="'+r.url+'">'+r.name+'</a></td><td>'+r.role+'</td><td>'+r.status+'</td><td>'+r.license+'</td></tr>').join('')}
function selectLabTab(id){
  if(!['compare','confirmed','principle','sources'].includes(id))return;
  for(const b of document.querySelectorAll('[data-tab]')){b.classList.toggle('active',b.dataset.tab===id);b.setAttribute('aria-selected',String(b.dataset.tab===id));}
  for(const panel of document.querySelectorAll('main>section[id^="tab-"]'))panel.hidden=panel.id!=='tab-'+id;
  if(id!=='compare')motionPause();
  requestAnimationFrame(draw);
}
for(const b of document.querySelectorAll('[data-tab]'))b.onclick=()=>selectLabTab(b.dataset.tab);
function channelSummary(){const c=result?.channels;if(!c)return;const q=c.reflectivityProxy;$('channels-summary').textContent=q.available?'반환점 '+fmt(c.pointCount)+'개 중 반사도 추정값 '+fmt(q.finiteCount)+'개 · 범위 '+q.range.map(x=>x==null?'없음':x.toPrecision(3)).join('~')+' · 미교정 모델값':'햇빛 신호·반사도: 미구현, 전체 null. 재질 참고값은 별도 출력됩니다.';Object.assign(right.host.dataset,{reflectivityAvailable:String(q.available),reflectivityFinite:String(q.finiteCount),channelsRevision:String(c.revision)});}
function parameterSummary(){
 const q=result?.config.parameterSampling,values=q?.parameters||{},names={rainRate:'강우량',snowN:'눈 수 농도',fogVisibility:'안개 가시거리'},units={rainRate:'mm/h',snowN:'개/m³',fogVisibility:'m'};
 const text=Object.entries(values).map(([k,v])=>names[k]+': 평균 '+v.mean.toFixed(2)+' / std '+v.std.toFixed(2)+' → 이번 값 '+v.value.toFixed(2)+units[k]+(v.clipped?' (조절 범위에서 제한됨)':'')).join(' · ');
 $('weather-parameter-active').textContent=text||'현재 선택: 먼지 발생량·햇빛 방향 및 확률 등은 노브값을 유지합니다. 입자 또는 반환 위치의 난수는 별도로 적용됩니다.';
 right.host.dataset.parameterSampling=JSON.stringify(q||{});
}
$('weather-jitter').onchange=()=>{motionPause();generate()};
function simpleUI(){
 $('weather-jitter-label').hidden=!['rain','snow','fog'].includes(category);
 parameterSummary();
  const motion=motionActive(),world=motion&&$('motion-view').value==='world';
  $('motion-view-control').hidden=!motion;
  $('real-caption').textContent=usesBeforeView()?'합성 장소 · 효과와 거리 오차 적용 전':['rain','snow'].includes(category)?'실측 · 점별 오류 라벨 없음':'주황: 제공자 라벨 · 생성 화면과 다른 장소';
  $('sim-caption').textContent=$('show-reflectivity').checked?'밝기: 반사도 추정값 · 회색: 미지원 또는 운동 표본':world?'주황: 운동 표본(관측점 아님) · 청록: 라이다 표면':category==='range'?'표면 위치 오차 · 삭제 정답 없음':category==='general'?'노랑: 변화한 표면 · 삭제 정답 아님':'주황: 합성 산란·오류 반환 · 청록: 표면';
  $('sun-v10-preset').hidden=category!=='sun';$('fog-v10-preset').hidden=category!=='fog';
  $('previous-presets').hidden=!['sun','fog'].includes(category);
  $('solar-stats').hidden=category!=='sun';$('motion-stats').hidden=!motion;
  $('atmosphere-note').hidden=$('atmosphere-stats').hidden=$('atmosphere-decision').hidden=!['fog','general'].includes(category);
  $('motion-note').hidden=!motion;
}

for(const s of D.scenes)$('sim-scene').add(new Option(s.title+' · 예시 '+s.variant,s.id));$('sim-scene').value='construction_v1';$('sim-scene').onchange=()=>{weatherAutoMoved=false;loadScene()};$('real-sample').onchange=loadReal;$('category').onchange=changeCategory;$('source-filter').onchange=sourceRows;$('scan-mode').onchange=()=>{if($('scan-mode').value!=='live')$('sensor-pose').value='legacy';loadScene()};$('surface-response').onchange=generate;
$('show-reflectivity').onchange=()=>{colors();simpleUI();};$('show-labels').onchange=colors;$('noise-only').onchange=colors;$('focus').onclick=()=>focus(false);$('whole').onclick=()=>{$('noise-only').checked=false;colors();focus(true)};$('side').onclick=()=>{shared.el=.08;draw()};$('new-seed').onclick=()=>{$('seed').value=(+$('seed').value+1)>>>0;generate()};$('advance').onclick=()=>{$('time').value=Math.min(5,+$('time').value+.5);generate()};let timer;for(const el of $('generator-controls').querySelectorAll('input'))el.oninput=()=>{clearTimeout(timer);++job;right.host.dataset.ready='false';timer=setTimeout(generate,180)};
function rangePanel(){
  const supported=activeCategory(),kind=result?.stats?.review?.kind;$('range-review').hidden=!supported||kind==='edge'||kind==='sun';if(!supported||!result||kind==='edge'||kind==='sun')return;
  $('range-review').querySelector('p').textContent=kind==='weak'?'약한 신호 모드가 적용한 거리 오차입니다. 신호량마다 표준편차가 달라지며 기존 60mm 노브는 적용하지 않습니다. 효과를 끄면 거리 흔들림과 미검출이 함께 해제됩니다.':'반환 위치를 빔 방향으로 흔듭니다. 기본 σ=60mm, k=0은 사용자가 시각 비교한 검토 설정이며 센서 실측값이 아닙니다. 끄면 같은 시드·장소·반환점의 오차 적용 전 좌표로 돌아갑니다.';
  const e=result.stats.rangeError,mm=x=>(1000*x).toFixed(2),clipped=e.surface.clipped+e.dust.clipped;
  $('range-summary').textContent=(e.enabled?'거리 오차 켬':'거리 오차 끔')+' · 표면 RMS '+mm(e.surface.rms)+'mm / 산란점 RMS '+(e.dust.n?mm(e.dust.rms)+'mm':'해당 없음')+' · 최소 거리 제한 '+clipped+'점';
  $('sim-info').textContent+=' 거리 오차 '+(e.enabled?'적용':'끔')+' · 표면 '+mm(e.surface.rms)+'mm, 산란점 '+(e.dust.n?mm(e.dust.rms)+'mm':'없음')+' RMS.';
  const selected=[];for(let type=0;type<2;type++){const ids=[];for(let i=0;i<result.labels.length;i++)if(result.labels[i]===type)ids.push(i);const count=Math.min(80,ids.length);for(let k=0;k<count;k++)selected.push(ids[Math.floor(k*ids.length/count)])}
  const xmax=Math.max(10,...selected.map(i=>result.nominalRanges[i])),ymax=Math.max(1,...selected.map(i=>Math.abs(result.rangeErrors[i]*1000)))*1.15;
  const W=660,H=190,L=62,T=20,PW=575,PH=130,X=r=>L+r/xmax*PW,Y=e=>T+PH/2-e/ymax*PH/2;
  let svg='<line x1="'+L+'" x2="'+(L+PW)+'" y1="'+Y(0)+'" y2="'+Y(0)+'" stroke="#66818e"/><line x1="'+L+'" x2="'+L+'" y1="'+T+'" y2="'+(T+PH)+'" stroke="#66818e"/>';
  for(const sign of [-1,0,1])svg+='<text x="55" y="'+(Y(sign*ymax)+4)+'" text-anchor="end" fill="#b7c9d1" font-size="11">'+(sign*ymax).toFixed(1)+'</text>';
  for(const i of selected)svg+='<circle cx="'+X(result.nominalRanges[i]).toFixed(2)+'" cy="'+Y(result.rangeErrors[i]*1000).toFixed(2)+'" r="2.2" fill="'+(result.labels[i]?'#ff875d':'#91b9c4')+'"/>';
  svg+='<text x="8" y="13" fill="#b7c9d1" font-size="11">오차 mm</text><text x="'+L+'" y="171" fill="#b7c9d1" font-size="11">0m</text><text x="'+(L+PW)+'" y="171" text-anchor="end" fill="#b7c9d1" font-size="11">'+xmax.toFixed(1)+'m</text><text x="345" y="185" text-anchor="middle" fill="#b7c9d1" font-size="11">오차 적용 전 거리 r</text>';
  $('range-plot').innerHTML=svg;
}
async function inflate(s){const bytes=Uint8Array.from(atob(s),c=>c.charCodeAt(0));return await new Response(new Blob([bytes]).stream().pipeThrough(new DecompressionStream('gzip'))).arrayBuffer()}
async function prepareScan(scene,profile){
  scene.scanProfile=profile;
  if(profile==='live'){scene.liveRaw=await data(D.geometry_knobs_v3.scenes.find(s=>s.scene===scene.id).id);scene.liveBeam=await data('beam_profiles_v2');scene.scanGeometry={profile:'live'};scene.scanInput=null;return;}
  if(profile==='ideal'){scene.scanInput={sensor:scene.sensor,ranges:scene.rangesArray};scene.scanGeometry={profile:'ideal',optical_offset_m:0};return}
  const beam=await data('beam_profiles_v2');if(!beam.dirs){beam.dirs=new Float32Array(await inflate(beam.directions));beam.offsets=new Float32Array(await inflate(beam.origins))}
  const raw=await data('scan_'+scene.id+'_'+profile);if(!raw.readyInput){
    const buf=await inflate(raw.payload),n=raw.n,range=new Float32Array(buf,0,n),response=new Float32Array(buf,n*4,n),ground=new Uint8Array(buf,n*8,n),dirs=new Float32Array(n*3),origins=new Float32Array(n*3),rot=raw.rotation;
    for(let i=0;i<n;i++){const k=i*3,col=(i%beam.w)*3,v=beam.dirs.subarray(k,k+3),o=raw.optical_offset?beam.offsets.subarray(col,col+3):beam.center_origin_m;for(let a=0;a<3;a++){dirs[k+a]=rot[a][0]*v[0]+rot[a][1]*v[1]+rot[a][2]*v[2];origins[k+a]=raw.sensor[a]+rot[a][0]*o[0]+rot[a][1]*o[1]+rot[a][2]*o[2]}}
    raw.readyInput={sensor:raw.sensor,ranges:range,response,ground,directions:dirs,origins};
  }
  scene.scanInput=raw.readyInput;scene.scanGeometry={profile,rotation:raw.rotation,optical_offset_m:raw.optical_offset?beam.optical_radius_m:0,beam_metadata_sha256:beam.metadata_sha256,beam_profile_sha256:D.beam_profile_sha256,scan_asset_sha256:D.scan_asset_sha256?.['scan_'+scene.id+'_'+profile],beam_sensor:'OS-1-128 public reference, not the displayed dust sensor',rays:raw.n,scene_seed:scene.seed};
}
function scanSummary(){
  setGeometryEnabled();if(simData.scanProfile==='live'){liveGeometrySummary();return;}
  const p=simData.scanProfile,geometry=simData.scanGeometry;
  $('surface-response').disabled=p==='ideal'||!activeCategory();
  $('scan-summary').textContent=p==='ideal'?'기존 가상 64×1,024 빔 · 한 점에서 출발 · 완전 평지 · 재질 반응 없음':
    '공개 OS1-128의 128×1,024 빔 · 광학 원점 반경 '+(1000*geometry.optical_offset_m).toFixed(3)+'mm · '+(p==='os1_terrain'?'장소별 합성 지면 굴곡 + 설치 기울기 가정':'수평 설치 + 기존 평지')+'. 왼쪽 먼지 실측의 센서 보정값은 아닙니다.';
  if(p==='os1_terrain'){const t=D.scan_geometry_v2.terrain.find(x=>x.scene===simData.id);$('scan-summary').textContent+=' 이 장소: 앞뒤 '+t.pitch_deg.toFixed(2)+'°, 좌우 '+t.roll_deg.toFixed(2)+'° / 지면 높이 표준편차 '+(t.height_std_m*100).toFixed(2)+'cm.'}
}
function viewBusy(message){
  right.host.dataset.ready='false';right.host.dataset.displayState=right.xyz?.length?'previous':'loading';
  $('view-status').textContent=message+(right.xyz?.length?' 아래에는 직전 결과가 잠시 남아 있습니다.':'');
  $('sim-overlay').textContent=message;$('view-retry').hidden=true;
}
function viewFailure(stage,error){
  motionPause();right.host.dataset.ready='error';right.host.dataset.displayState='error';
  $('view-status').textContent=stage+' 실패. 설정을 유지한 채 다시 표시할 수 있습니다.';
  $('sim-overlay').textContent=stage+' 실패 · 위의 다시 표시를 눌러 주세요.';
  $('sim-info').textContent=String(error);$('view-retry').hidden=false;
}
function cancelViewWork(){
  motionPause();clearTimeout(timer);clearTimeout(geometryTimer);++job;++geoJob;
  worker.cancel();geometryWorker.cancel();geoPending='';
}
$('view-retry').onclick=()=>loadScene();
__WEATHER_CLIENT__
__MOTION_CLIENT__
__SOLAR_CLIENT__
__ATMOSPHERE_CLIENT__
__GEOMETRY_CLIENT__
__NAVIGATION_V9__
__FULLRANGE_CLIENT_V10__
__SEQUENCE_CLIENT_V21__
$('motion-view').addEventListener('change',simpleUI);
initAvailability();
if(['spray','reflection'].includes(new URLSearchParams(location.search).get('kind'))){
  $('redirect-note').textContent='이 항목의 생성 한계는 이 탭에 모았습니다. 3D 탭에서는 계산 가능한 종류를 선택하세요.';
  selectLabTab('confirmed');
}

const initialCategory=new URLSearchParams(location.search).get('kind');if([...$('category').options].some(o=>o.value===initialCategory))$('category').value=initialCategory;
if(new URLSearchParams(location.search).get('view')==='world')$('motion-view').value='world';
sourceRows();changeCategory();loadScene();
