function solarConfig(){return {patternLegacy:$('pattern-legacy').checked,receiverMode:category==='sun'?$('solar-mode').value:$('receiver-mode').value,solarEnabled:category==='sun',solarMode:$('solar-mode').value,sunAz:+$('sunAz').value,sunEl:+$('sunEl').value,sunIrradiance:+$('sunIrradiance').value};}
function solarControls(){
 $('pattern-controls').hidden=!motionActive();$('legacy-source-label').hidden=category!=='dust';$('solar-controls').hidden=category!=='sun';if(category!=='sun')return;
 for(const id of ['sunAz','sunEl','sunIrradiance'])$(id+'-out').textContent=$(id).value;
 $('generated-title').textContent=$('solar-mode').value==='reference'?'햇빛 · Ouster 실측 참고':'햇빛 · 가상 수광기 실험';
 $('noise-only').disabled=false;$('mode-note').textContent='OS1-32의 해당 실측 실험에서는 햇빛 유발 가짜점이 관찰되지 않았습니다. 기본 모드에는 합성 가짜점을 넣지 않습니다. 가상 수광기는 다른 장비의 재현도 아니며 광학·전자회로 가정을 검토하는 실험입니다.';
}
function solarSummary(){if(category!=='sun'||!result?.solar)return;const v=result.solar,s=v.stats,c=v.config,ref=c.mode==='reference';
 $('sim-overlay').textContent=ref?'실측 근거 참고 · 햇빛 합성점 0':'가상 수광기 · 배경광 반환 '+fmt(result.stats.receiver.backgroundReturns)+'점';
 $('sim-info').textContent=ref?'태양 실측 원본은 미확보입니다. 오른쪽은 변화시키지 않은 장소 참고이며 햇빛 성능을 예측한 결과가 아닙니다.':'광자 검출 가정으로 계산한 결과입니다. 표면 '+fmt(result.stats.surface)+'점 · 누락 '+fmt(result.stats.lost)+'점. 범위 초과 '+fmt(s.unsupportedRays)+'빔은 예측에서 제외하고 원래 형상을 유지합니다.';
 $('solar-stats').textContent='예상 배경: 평균 '+s.meanPhotons.toFixed(2)+' · 최대 '+s.maxPhotons.toFixed(1)+'광자/구간 · 태양 원반 방향 '+s.directSunRays+'빔 · 범위 초과 '+s.unsupportedRays+'빔'+(ref?' · 배경광 지도만 계산':' · 검출 문턱 '+result.stats.receiver.minThreshold+'~'+result.stats.receiver.maxThreshold);
 const canvas=$('solar-map'),ctx=canvas.getContext('2d'),w=canvas.width/72,h=180/36,max=Math.log1p(Math.max(...v.angular));ctx.fillStyle='#071019';ctx.fillRect(0,0,720,220);for(let y=0;y<36;y++)for(let x=0;x<72;x++){const j=y*72+x;if(!v.angularCounts[j])continue;const f=Math.log1p(v.angular[j])/(max||1);ctx.fillStyle='hsl('+(205-170*f)+',80%,'+(20+45*f)+'%)';ctx.fillRect(x*w,(35-y)*h,w,h);}ctx.fillStyle='#ffe993';ctx.beginPath();ctx.arc((c.azimuth+180)/360*720,(90-c.elevation)/180*180,5,0,Math.PI*2);ctx.strokeStyle='#fff';ctx.stroke();ctx.font='12px sans-serif';ctx.fillText('○ 태양 방향 · 검은 칸: 빔 없음 · 같은 화면의 상대 밝기',8,205);
 Object.assign(right.host.dataset,{solarMode:c.mode,solarUnsupported:String(s.unsupportedRays),solarDirect:String(s.directSunRays),solarBackgroundReturns:String(result.stats.receiver?.backgroundReturns||0),receiverMode:result.config.receiverMode,version:'v7'});
}
function solarFeatures(){const ref=$('solar-mode').value==='reference';$('features').innerHTML='<div class="card"><h3>실측 근거</h3><p>FZD 2022의 OS1-32에서는 햇빛 유발 가짜점이 관찰되지 않았습니다. 다른 모델·조건까지 보장하지는 않습니다.</p><a href="https://www.mdpi.com/1424-8220/22/14/5266" target="_blank">센서 비교 논문</a></div><div class="card"><h3>현재 선택</h3><p>'+(ref?'실측 결과 참고: 합성 오류를 강제로 넣지 않습니다.':'가상 수광기: 표면 조명과 하늘 배경 → 광자 수 → 거리 구간별 검출. Ouster 교정 모델이 아닙니다.')+'</p></div><div class="card"><h3>아직 못 만드는 부분</h3><p>직사광 포화·전자회로·광학 플레어·반사광 오류는 미검증입니다. 범위 초과 빔은 예측하지 않습니다.</p></div>';$('feature-note').textContent='수치 검사와 현장 재현 검증은 다릅니다. 식·상수·모델 경계는 ‘생성 원리’에 공개했습니다. 학습 승인 없음.';}
for(const id of ['receiver-mode','pattern-legacy','solar-mode','sunAz','sunEl','sunIrradiance'])$(id).oninput=()=>{motionPause();solarControls();clearTimeout(timer);++job;right.host.dataset.ready='false';timer=setTimeout(generate,220);};
