const atmosphereIds=['fogScatterLog','fogVisibility','fogRatio','fogPulse','fogNear','fogFull','fogVariation','weakPhotons','edgePulse','edgeBeam'];
function atmosphereActive(){return category==='fog'||category==='general';}
function atmosphereConfig(){const kind=category==='fog'?'fog':category==='general'&&$('general-mode').value!=='none'?$('general-mode').value:'';const c={reviewKind:kind,reviewEnabled:$('review-enabled').checked,fogBackscatter:$('fogBackscatter').checked,fogScatterResponse:10**(+$('fogScatterLog').value)};for(const id of atmosphereIds)c[id]=+$(id).value;if(kind==='weak'||kind==='edge'){c.radialSigma=0;c.radialSlope=0;}return c;}
function atmosphereControls(){
 $('atmosphere-controls').hidden=!atmosphereActive();if(!atmosphereActive())return;const kind=atmosphereConfig().reviewKind;
 $('general-mode-label').hidden=category!=='general';$('fog-knobs').hidden=kind!=='fog';$('edge-knobs').hidden=kind!=='edge';$('weak-knobs').hidden=kind!=='weak';$('review-enabled').disabled=!kind;$('wave-details').hidden=!['fog','edge'].includes(kind);$('weather-controls').hidden=true;
 for(const id of atmosphereIds)if($(id+'-out'))$(id+'-out').textContent=$(id).value;
 if(kind==='edge'||kind==='weak')for(const id of ['range-enabled','radialSigma','radialSlope'])$(id).disabled=true;
 $('fogScatterLog-out').textContent=(100*10**(+$('fogScatterLog').value)).toFixed(3)+'%';
 $('generated-title').textContent={fog:$('fogBackscatter').checked?'안개 · 확률적 산란·감쇠 후보':'안개 · 감쇠만 비교',edge:'경계 혼합 · 노란 보정 후보',weak:'약한 신호 · 표면 오차와 누락'}[kind]||'원인 불명 · 생성 보류';
 $('mode-note').textContent=category==='general'?'같은 합성 장소의 효과 전후를 비교합니다. 노란 점은 중심 빔과 달라진 반환이며 삭제 정답이 아닙니다. 약한 신호의 흔들린 점도 표면 라벨을 유지합니다.':'안개의 산란 신호와 약해진 표면 신호에서 확률적으로 반환을 선택합니다. 첫 물체 앞의 전 거리 구간을 계산하며 가장 강한 거리만 반복 선택하지 않습니다. Ouster 수광 회로 재현은 아닙니다.';
 $('atmosphere-note').textContent={fog:'가시거리는 감쇠·농도 가정이고, 반환 민감도는 넓게 퍼진 안개 신호가 수광기 계산에 들어가는 상대 비율입니다. 기본 약한 효과는 실측 교정값이 아닙니다. 이전 과밀 설정은 비교 버튼으로만 불러옵니다.',edge:'실제 메시를 13개 부광선으로 관측합니다. 노란색은 펄스 혼합 또는 앞·뒤 다른 표면 선택으로 중심 빔과 달라진 점입니다. 최대 차이는 센서 정밀도 오차가 아니며, 경계점 전체를 제거하는 학습에는 쓰지 않습니다.',weak:'약한 신호일수록 표면 거리가 더 흔들리고 검출이 빠질 수 있습니다. 유지한 점은 모두 표면 라벨을 보존합니다. 기존 60mm 거리 노브는 중복 적용하지 않습니다.'}[kind]||'생성하지 않습니다. Class 7의 오분류·원인이 확인되지 않아, 그 모양을 복사하면 실제 물체를 삭제하도록 학습시킬 위험이 있습니다.';
 $('atmosphere-decision').textContent=kind==='fog'?'검토 전용: 반환 민감도를 임시로 낮춘 설정입니다. 점이 줄었다는 사실은 현실성 검증이 아닙니다. 센서 실측으로 교정하기 전에는 학습에 사용하지 않습니다.':kind?'현재 판정: 원리 검토 후보 · 센서 교정과 실측 검증 전에는 학습에서 제외':'현재 판정: 생성 보류 · 원인·라벨 검증이 먼저 필요';
 $('noise-only').disabled=kind==='weak';if(kind==='weak')$('noise-only').checked=false;
}
function atmosphereSummary(){if(!atmosphereActive())return;atmosphereControls();const s=result.stats,q=s.review,kind=atmosphereConfig().reviewKind;Object.assign(right.host.dataset,{reviewKind:kind||'none',reviewEnabled:String(!!q?.enabled),uncertain:String(s.uncertain||0),version:'v8',fieldValidated:'false',training:'false'});
 if(!q){$('sim-overlay').textContent='원인 불명 · 합성 이상점 0';$('sim-info').textContent='원인 불명의 실측 라벨을 흉내 내지 않았습니다. 일반 이상점의 원인을 선택하면 별도 원리 후보를 볼 수 있습니다.';$('atmosphere-stats').textContent='';return;}
 $('sim-overlay').textContent={fog:'안개 반환 '+fmt(s.dust)+'점 · 혼합 '+fmt(s.uncertain)+'점',edge:'거리 편향 후보 '+fmt(q.mixed||0)+'점',weak:'삭제 정답 0점 · 미검출 '+fmt(s.lost)+'점'}[kind];
 $('sim-info').textContent='표면·보정 후보 '+fmt(s.surface)+'점 · 산란 '+fmt(s.dust)+'점 · 산란으로 대체된 표면 '+fmt(s.replaced)+'점 · 반환 자체가 없는 표면 '+fmt(s.lost)+'점. 노란색 '+fmt(s.uncertain||0)+'점은 제거 정답이 아닙니다.';
 $('atmosphere-stats').textContent=kind==='fog'?'반환 민감도 '+(100*(q.scatterResponse??1)).toFixed(3)+'% · α '+q.alpha.toFixed(4)+'m⁻¹ · 생성 산란점의 가장 조밀한 1m 거리 구간 '+(100*(q.shellFraction||0)).toFixed(1)+'%':kind==='edge'?'부광선 묶음 '+fmt(q.bundles)+'개 · 중심 광선 대비 최대 거리 차이 '+q.maxBias.toFixed(3)+'m':'유지점의 평균 거리 표준편차 가정 '+(q.meanSigma*1000).toFixed(1)+'mm · 표면 라벨 보존';
 if(q.shellWarning)$('atmosphere-decision').textContent='학습 제외: 산란점이 좁은 거리 껍질에 집중됩니다. 실측에서 같은 센서 응답이 확인되기 전에는 이 패턴을 학습시키지 않습니다.';
 const t=q.trace,canvas=$('review-wave'),ctx=canvas.getContext('2d');ctx.clearRect(0,0,700,200);if(!t){$('wave-caption').textContent='이 설정에서 표시할 반환 예시가 없습니다.';return;}
 const xs=[],a=[],b=[];if(kind==='fog'){for(let j=0;j<t.soft.length;j++){xs.push((j+.5)*t.rangeStep);a.push(t.soft[j]);b.push(t.solid[j]);}}else{const sig=299792458*q.config.edgePulseNs*1e-9/(2*2.35482),lo=Math.min(...t.echoes.map(e=>e.range))-3*sig,hi=Math.max(...t.echoes.map(e=>e.range))+3*sig;for(let j=0;j<250;j++){const x=lo+(hi-lo)*j/249;xs.push(x);a.push(t.echoes.reduce((s,e)=>s+e.power*Math.exp(-.5*((x-e.range)/sig)**2),0));b.push(0);}}
 const xmax=kind==='fog'?Math.min(100,Math.max(10,t.target+5)):Math.max(...xs),xmin=kind==='fog'?0:Math.min(...xs),max=Math.max(...a,...b)||1,X=x=>40+(x-xmin)/(xmax-xmin)*640,Y=y=>170-y/max*140;
 for(const [values,color] of [[a,'#ff9867'],[b,'#95d7dd']]){ctx.beginPath();let started=false;for(let j=0;j<xs.length;j++){if(xs[j]>xmax)break;if(!started){ctx.moveTo(X(xs[j]),Y(values[j]));started=true;}else ctx.lineTo(X(xs[j]),Y(values[j]));}ctx.strokeStyle=color;ctx.stroke();}ctx.strokeStyle='#ffe077';ctx.beginPath();ctx.moveTo(X(t.selected),20);ctx.lineTo(X(t.selected),170);ctx.stroke();ctx.fillStyle='#d7e6ed';ctx.font='12px sans-serif';ctx.fillText(xmin.toFixed(1)+'m',40,190);ctx.fillText(xmax.toFixed(1)+'m',640,190);
 $('wave-caption').textContent=kind==='fog'?'주황: 안개 평균 신호 · 청록: 물체 평균 신호 · 노랑 선: 광자 변동 후 선택한 거리. 물체 '+t.target.toFixed(2)+'m / 선택 '+t.selected.toFixed(2)+'m.':'주황: 여러 표면의 펄스를 더한 신호 · 노랑 선: 최고점 거리. 중심 광선 '+t.target.toFixed(3)+'m / 선택 '+t.selected.toFixed(3)+'m. 센서의 실제 수신 파형이 아닙니다.';
}
function atmosphereFeatures(){const kind=atmosphereConfig().reviewKind;const rows=kind==='fog'?[['현재 3D에 적용','광자 도착 확률에 따른 전 거리 산란·표면 반환과 감쇠'],['학습 보류 이유','해당 센서의 안개 실측과 광학 응답 미확보. 거리 껍질을 그대로 외울 위험.'],['모델로 못 푸는 것','가려진 물체의 실제 형상은 이 관측만으로 결정할 수 없습니다.']]:kind==='edge'?[['구현한 것','경계 부광선의 실제 표면 교차와 펄스 혼합'],['학습 보류 이유','단순한 경계점 삭제는 작은 물체·가지·모서리를 손상시킬 수 있습니다.'],['다음 검증에 필요한 것','해당 센서의 서로 다른 깊이·반사율 경계 실측과 깨끗한 기준 형상']]:kind==='weak'?[['구현한 것','신호량에 따른 거리 분산과 검출 누락'],['삭제 학습에 부적합','반환된 점은 실제 표면입니다. 위치 보정·불확실성 대상으로 검토합니다.'],['다음 검증에 필요한 것','평면 표적을 거리·입사각·반사율별로 반복 측정한 오차 분포']]:[['원인 미확인','Class 7을 특정 센서 오류라고 단정할 수 없습니다.'],['합성하지 않는 이유','확인되지 않은 라벨 모양을 복사하면 구조물까지 오류로 배울 수 있습니다.'],['대안','원인이 정의된 후보를 따로 검토하고 원본 라벨은 그대로 보존합니다.']];$('features').innerHTML=rows.map(([a,b])=>'<div class="card"><h3>'+a+'</h3><p>'+b+'</p></div>').join('');$('feature-note').textContent='계산 가능하다는 것과 학습에 유익하다는 것은 별개입니다. 이번에는 모델 학습을 실행하지 않았고, 모든 후보는 실측 검증 전입니다.';}
for(const id of [...atmosphereIds,'general-mode','review-enabled','fogBackscatter'])$(id).oninput=()=>{motionPause();setGeometryEnabled();atmosphereControls();clearTimeout(timer);++job;right.host.dataset.ready='false';timer=setTimeout(generate,220);};

for(const [id,visibility,log] of [["fog-soft-preset",500,-3.3],["fog-v10-preset",100,0]])$(id).onclick=()=>{motionPause();$("fogVisibility").value=visibility;$("fogScatterLog").value=log;$("fogBackscatter").checked=true;$("review-enabled").checked=true;atmosphereControls();generate();};
