/* Display only. Physics and observed coordinates come from the runtime exports. */
(function(global){
'use strict';
const T=global.THREE,cache=new Map();
async function inflate(bytes){return new Response(new Blob([bytes]).stream().pipeThrough(new DecompressionStream('gzip'))).arrayBuffer();}
async function unpack(s,Type){return new Type(await inflate(Uint8Array.from(atob(s),c=>c.charCodeAt(0))));}
async function loadGeometry(row){
 if(cache.has(row.id))return cache.get(row.id);
 const pending=(async()=>{await NoiseLabScene.warm();const r=await fetch('assets/noise_lab_v1/'+row.geometry.id+'.json');if(!r.ok)throw Error('장소 형상을 읽지 못했습니다.');const raw=await r.json();const [v,f,rho,tv,tf]=await Promise.all([unpack(raw.vertices,Float32Array),unpack(raw.faces,Uint32Array),unpack(raw.rho,Float32Array),unpack(raw.terrain.vertices,Float32Array),unpack(raw.terrain.faces,Uint32Array)]);return {raw,v,f,rho,tv,tf};})();
 cache.set(row.id,pending);if(cache.size>3)cache.delete(cache.keys().next().value);return pending;
}
function dispose(group){if(!group)return;group.traverse(o=>{o.geometry?.dispose();if(Array.isArray(o.material))o.material.forEach(m=>m.dispose());else o.material?.dispose();});group.parent?.remove(group);}
function geometry(v,f){const g=new T.BufferGeometry();g.setAttribute('position',new T.BufferAttribute(v,3));g.setIndex(new T.BufferAttribute(f,1));g.computeVertexNormals();return g;}
function meshGroup(data){
 const group=new T.Group(),objects=new T.Mesh(geometry(data.v,data.f),new T.MeshStandardMaterial({color:0xa4b8b5,roughness:.9,metalness:0,side:T.DoubleSide})),ground=new T.Mesh(geometry(data.tv.slice(),data.tf),new T.MeshStandardMaterial({color:0x536963,roughness:1,side:T.DoubleSide}));
 group.add(objects,ground);group.userData={objects,ground,data};return group;
}
function terrain(group,cm){const {ground,data}=group.userData,p=ground.geometry.attributes.position,scale=cm/100/data.raw.terrain.base_std_m;for(let i=2;i<p.array.length;i+=3)p.array[i]=data.tv[i]*scale;p.needsUpdate=true;ground.geometry.computeVertexNormals();ground.geometry.computeBoundingSphere();}
function clip(group,on){const m=group.userData.objects.material;m.clippingPlanes=on?[new T.Plane(new T.Vector3(0,0,-1),2.25)]:[];m.needsUpdate=true;}
function lighting(scene){scene.add(new T.HemisphereLight(0xc8e7ff,0x354b35,2.6));const light=new T.DirectionalLight(0xffebd5,2.8);light.position.set(-20,-30,70);scene.add(light);}
function indoor(row){return !['construction','crane_yard','apartment'].includes(row.family);}
function bounds(object){return new T.Box3().setFromObject(object);}
class ReviewViewer{
 constructor(host){
  this.host=host;this.scene=new T.Scene();this.scene.background=new T.Color(0x0b151d);lighting(this.scene);this.camera=new T.PerspectiveCamera(48,1,.03,2000);this.camera.up.set(0,0,1);this.renderer=new T.WebGLRenderer({antialias:true,alpha:false});this.renderer.setPixelRatio(Math.min(devicePixelRatio,2));this.renderer.localClippingEnabled=true;host.appendChild(this.renderer.domElement);
  this.target=new T.Vector3();this.az=-1.15;this.el=.78;this.radius=40;this.opts={display:'combined',color:'reflectivity',cutaway:false,path:true,poses:false,particles:false,noise:false,size:2};this.version=0;
  let drag=null;host.addEventListener('contextmenu',e=>e.preventDefault());host.addEventListener('pointerdown',e=>{drag={x:e.clientX,y:e.clientY,pan:e.button===2||e.shiftKey};host.setPointerCapture(e.pointerId);});host.addEventListener('pointerup',()=>drag=null);host.addEventListener('pointercancel',()=>drag=null);host.addEventListener('pointermove',e=>{if(!drag)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;drag.x=e.clientX;drag.y=e.clientY;if(drag.pan){const right=new T.Vector3().setFromMatrixColumn(this.camera.matrix,0),up=new T.Vector3().setFromMatrixColumn(this.camera.matrix,1);this.target.addScaledVector(right,-dx*this.radius/600).addScaledVector(up,dy*this.radius/600);}else{this.az-=dx*.006;this.el=Math.max(.04,Math.min(1.56,this.el+dy*.006));}this.render();});host.addEventListener('wheel',e=>{e.preventDefault();this.radius=Math.max(.3,Math.min(1200,this.radius*Math.exp(e.deltaY*.001)));this.render();},{passive:false});
  this.renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();host.dataset.context='lost';document.getElementById('viewer-caption').textContent='3D 연결이 중단되었습니다. 페이지를 새로고침해 주세요. 저장된 결과는 보존됩니다.';});
  new ResizeObserver(()=>this.resize()).observe(host);this.resize();
 }
 resize(){const w=this.host.clientWidth,h=this.host.clientHeight;if(!w||!h)return;this.renderer.setSize(w,h,false);this.camera.aspect=w/h;this.camera.updateProjectionMatrix();this.render();}
 render(){this.camera.position.set(this.target.x+this.radius*Math.cos(this.el)*Math.cos(this.az),this.target.y+this.radius*Math.cos(this.el)*Math.sin(this.az),this.target.z+this.radius*Math.sin(this.el));this.camera.lookAt(this.target);this.renderer.render(this.scene,this.camera);}
 async setScene(row){const ticket=++this.version;this.clearObservation();dispose(this.mesh);dispose(this.poses);this.mesh=null;this.poses=null;this.row=row;this.render();const data=await loadGeometry(row);if(ticket!==this.version)return;this.baseData=data;this.layoutKey=null;this.mesh=meshGroup(data);this.scene.add(this.mesh);this.host.dataset.scene=row.id;terrain(this.mesh,row.geometry.defaults.terrainCm);this.makePoses();this.opts.cutaway=indoor(row);this.update();this.fitScene();}
 makePoses(){dispose(this.poses);if(!this.mesh)return;const points=[],ray=new T.Raycaster();this.mesh.updateMatrixWorld(true);for(const p of this.row.poses){ray.set(new T.Vector3(p.x,p.y,200),new T.Vector3(0,0,-1));const hit=ray.intersectObject(this.mesh.userData.ground)[0];points.push(p.x,p.y,(hit?hit.point.z:0)+p.height);}this.poses=new T.Points(new T.BufferGeometry().setAttribute('position',new T.Float32BufferAttribute(points,3)),new T.PointsMaterial({color:0xc19afa,size:7,sizeAttenuation:false,depthTest:false}));this.scene.add(this.poses);}
 clearObservation(){for(const k of ['cloud','particles','route','sensor','emitter']){dispose(this[k]);this[k]=null;}this.frame=null;this.preview=null;if(this.layoutKey&&this.baseData){dispose(this.mesh);this.mesh=meshGroup(this.baseData);this.scene.add(this.mesh);terrain(this.mesh,this.row.geometry.defaults.terrainCm);this.layoutKey=null;this.makePoses();}this.host.dataset.props='0';this.host.dataset.pose='';this.host.dataset.time='';this.host.dataset.skew='';this.host.dataset.hash='';this.host.dataset.points='0';this.host.dataset.routePoints='0';this.update();}
 setPreview(p){if(!this.mesh||!p)return;
const layout=p.sceneLayout;if((layout?.key||null)!==this.layoutKey){const d=this.baseData,raw={...d.raw,vertices:d.v,faces:d.f,rho:d.rho,terrain:{...d.raw.terrain,vertices:d.tv,faces:d.tf}},merged=NoiseLabScene.compose(raw,layout);dispose(this.mesh);this.mesh=meshGroup({...d,v:merged.vertices,f:merged.faces,rho:merged.rho});this.scene.add(this.mesh);this.layoutKey=layout?.key||null;this.host.dataset.props=String(layout?.instances.length||0);}
this.preview=p;if(p.geometry?.terrainCm!==undefined){terrain(this.mesh,p.geometry.terrainCm);this.makePoses();}dispose(this.route);const points=(p.routePreview||[]).map(q=>new T.Vector3(...q.world));this.route=new T.Line(new T.BufferGeometry().setFromPoints(points),new T.LineBasicMaterial({color:0x65f1bb,depthTest:false}));this.route.renderOrder=5;this.scene.add(this.route);this.host.dataset.routePoints=String(points.length);this.setSensor(p.sensorPose);dispose(this.emitter);const source=p.sequencePlan?.dustSource;if(source){const v=Array.isArray(source)?source:[source.x,source.y,source.z];if(v.every(Number.isFinite)){this.emitter=new T.Mesh(new T.OctahedronGeometry(.35),new T.MeshBasicMaterial({color:0xebc975,depthTest:false}));this.emitter.renderOrder=6;this.emitter.position.set(...v);this.scene.add(this.emitter);}}this.update();}
 setSensor(p){dispose(this.sensor);this.sensor=null;if(!p?.world)return;const group=new T.Group(),dot=new T.Mesh(new T.SphereGeometry(.18,10,8),new T.MeshBasicMaterial({color:0xffffff,depthTest:false}));dot.position.set(...p.world);group.add(dot);const a=(p.yawDeg||0)*Math.PI/180,m=p.bodyRotation;group.add(new T.ArrowHelper(m?new T.Vector3(m[0],m[3],m[6]):new T.Vector3(Math.cos(a),Math.sin(a),0),new T.Vector3(...p.world),2,0xffffff,.45,.24));if(m)for(const [k,color]of [[1,0x66dd99],[2,0x6699ff]])group.add(new T.ArrowHelper(new T.Vector3(m[k],m[3+k],m[6+k]),new T.Vector3(...p.world),.9,color,.2,.1));group.traverse(o=>o.renderOrder=6);this.sensor=group;this.scene.add(group);}
 setFrame(frame){this.frame=frame;const m=frame.metadata,a=frame.arrays;this.setPreview({geometry:m.geometry,sensorPose:m.sensorPose,routePreview:m.routePreview,sequencePlan:m.sequencePlan,sceneLayout:m.sceneLayout});dispose(this.cloud);const g=new T.BufferGeometry();g.setAttribute('position',new T.BufferAttribute(a.xyz,3));this.cloud=new T.Points(g,new T.PointsMaterial({vertexColors:true,size:this.opts.size,sizeAttenuation:false,depthWrite:false}));this.cloud.frustumCulled=false;this.scene.add(this.cloud);dispose(this.particles);this.particles=null;if(a.world?.length){this.particles=new T.Points(new T.BufferGeometry().setAttribute('position',new T.BufferAttribute(a.world,3)),new T.PointsMaterial({color:0xf9aa63,size:2,sizeAttenuation:false,transparent:true,opacity:.5,depthWrite:false}));this.particles.frustumCulled=false;this.scene.add(this.particles);}this.host.dataset.skew=String(m.scanTiming?.enabled===true);this.host.dataset.hash=m.xyz_labels_sha256;this.host.dataset.points=String(a.labels.length);this.host.dataset.time=String(m.time);this.host.dataset.pose=JSON.stringify(m.sensorPose);this.colorPoints();this.update();}
 colorPoints(){if(!this.cloud||!this.frame)return;const a=this.frame.arrays,n=a.labels.length,c=new Float32Array(n*3),keep=[];for(let i=0;i<n;i++){let color=[.57,.76,.81];if(this.opts.color==='labels')color=a.labels[i]===1?[1,.40,.17]:a.labels[i]===2?[1,.82,.25]:color;else if(this.opts.color==='reflectivity'){const value=a.reflectivityProxy?.[i];color=Number.isFinite(value)?[Math.min(1,value),.3+.5*Math.min(1,value),1-Math.min(1,value)]:[.5,.5,.5];}c.set(color,i*3);if(a.labels[i]>0)keep.push(i);}this.cloud.geometry.setAttribute('color',new T.BufferAttribute(c,3));this.cloud.geometry.setIndex(this.opts.noise?keep:null);}
 setOptions(o){const recolor=o.color!==undefined||o.noise!==undefined;Object.assign(this.opts,o);this.host.dataset.colorMode=this.opts.color;if(recolor)this.colorPoints();this.update();}
 update(){const o=this.opts;if(this.mesh){this.mesh.visible=o.display!=='points';clip(this.mesh,o.cutaway);for(const m of this.mesh.children){m.material.transparent=o.display==='combined'&&!!this.cloud;m.material.opacity=m.material.transparent?.24:1;m.material.depthWrite=!m.material.transparent;}}if(this.cloud){this.cloud.visible=o.display!=='mesh';this.cloud.material.size=o.size;this.cloud.material.clippingPlanes=o.cutaway?[new T.Plane(new T.Vector3(0,0,-1),2.25)]:[];this.cloud.material.needsUpdate=true;}if(this.particles)this.particles.visible=o.particles;if(this.route)this.route.visible=o.path;if(this.sensor)this.sensor.visible=o.path;if(this.emitter)this.emitter.visible=o.path&&this.frame?.metadata.kind==='dust';if(this.poses)this.poses.visible=o.poses;this.render();}
 fitBox(b){if(b.isEmpty())return;const s=b.getSize(new T.Vector3());b.getCenter(this.target);this.radius=Math.max(8,Math.max(s.x,s.y,s.z)*1.45);this.render();}
 fitScene(){if(this.mesh)this.fitBox(bounds(this.mesh));}
 fitRoute(){if(this.route&&this.preview?.routePreview?.length){const b=bounds(this.route).expandByScalar(4);this.fitBox(b);}else this.fitScene();}
 fitSource(){if(this.emitter){this.target.copy(this.emitter.position);this.radius=16;this.render();}}
 top(){this.el=1.56;this.render();}
}
async function thumbnails(rows,onImage,onError){
 const renderer=new T.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});renderer.setSize(510,300,false);renderer.localClippingEnabled=true;const scene=new T.Scene();scene.background=new T.Color(0x10212b);lighting(scene);const camera=new T.PerspectiveCamera(45,510/300,.1,2000);camera.up.set(0,0,1);
 try{for(const row of rows){let group;try{group=meshGroup(await loadGeometry(row));clip(group,indoor(row));scene.add(group);const b=bounds(group),c=b.getCenter(new T.Vector3()),s=b.getSize(new T.Vector3()),r=Math.max(8,Math.max(s.x,s.y,s.z)*1.5);camera.position.copy(c).add(new T.Vector3(.5,-.65,.8).normalize().multiplyScalar(r));camera.lookAt(c);renderer.render(scene,camera);onImage(row,renderer.domElement.toDataURL('image/png'));}catch(e){onError(row,e);}finally{dispose(group);}await new Promise(r=>setTimeout(r,15));}}finally{renderer.dispose();renderer.forceContextLoss();}
}
async function readFrame(url){const response=await fetch(url);if(!response.ok)throw Error('프레임 파일을 읽지 못했습니다.');let buffer=await response.arrayBuffer();if(new Uint8Array(buffer)[0]===31)buffer=await inflate(buffer);const bytes=new Uint8Array(buffer),view=new DataView(buffer);if(new TextDecoder().decode(bytes.slice(0,4))!=='LSF1')throw Error('LSF 형식 오류');const n=view.getUint32(4,true);if(n>buffer.byteLength-8)throw Error('LSF 헤더 오류');const metadata=JSON.parse(new TextDecoder().decode(bytes.slice(8,8+n))),arrays={},types={Float32Array,Float64Array,Uint8Array,Uint32Array};for(const [name,e]of Object.entries(metadata.binary.arrays)){const Type=types[e.type];if(!Type||e.bytes!==e.length*Type.BYTES_PER_ELEMENT||e.offset<0||8+n+e.offset+e.bytes>buffer.byteLength)throw Error('LSF 배열 오류: '+name);arrays[name]=new Type(buffer.slice(8+n+e.offset,8+n+e.offset+e.bytes));}const combined=new Uint8Array(arrays.xyz.byteLength+arrays.labels.byteLength);combined.set(new Uint8Array(arrays.xyz.buffer));combined.set(arrays.labels,arrays.xyz.byteLength);const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',combined)),v=>v.toString(16).padStart(2,'0')).join('');if(hash!==metadata.xyz_labels_sha256)throw Error('관측 좌표·라벨 해시 불일치');return {metadata,arrays};}
global.ReviewDisplay={ReviewViewer,thumbnails,readFrame,indoor};
})(window);
