(async function(){
'use strict';
const $=id=>document.getElementById(id),D=window.ReviewDisplay;let catalog,viewer,row,job=null,playing=false,playTimer=null,selection=0,seekTicket=0,sceneTicket=0,pollTimer=null,previewKey='',sceneLoading=false;const frameCache=new Map(),values={};
const descriptors={dustFlux:['먼지 발생량',0,2,.05,.2,'g/s'],dustSize:['대표 입경',5,25,1,15,'µm'],motionEddy:['회오리 세기',0,1.5,.05,.7,''],rainRate:['강우량',1,20,1,5,'mm/h'],snowN:['눈 농도',1,10,.5,3,'개/m³'],fogVisibility:['가시거리',50,2000,25,500,'m'],fogVariation:['농도 불균일',0,.8,.05,.25,''],motionWind:['바람 속도',0,6,.1,1,'m/s'],motionAngle:['바람 방향',-180,180,5,35,'°'],sunAz:['태양 방위',-180,180,1,40,'°'],sunEl:['태양 고도',-10,80,1,10,'°'],sunWidth:['방향 폭',.5,8,.5,2,'°'],sunProbability:['중심 방향 오류 확률',0,1,.005,.05,''],weakPhotons:['기준 신호량',20,500,20,100,'광자']};
const modelKeys={range:[],dust:['dustFlux','dustSize','motionWind','motionAngle','motionEddy'],rain:['rainRate','motionWind','motionAngle'],snow:['snowN','motionWind','motionAngle'],fog:['fogVisibility','fogVariation','motionWind','motionAngle'],sun:['sunAz','sunEl','sunWidth','sunProbability'],edge:[],weak:['weakPhotons']};
function el(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;}
function status(text,error=false){$('job-status').textContent=text;$('job-status').classList.toggle('error',error);}
function fail(e){status(e.message||String(e),true);}
async function api(url,body){const r=await fetch(url,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json','X-Lidar-Review':'1'},body:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw Error(data.error||'서버 오류');return data;}
function tab(name){document.querySelectorAll('.tab').forEach(n=>n.hidden=n.id!==name);document.querySelectorAll('nav [data-tab]').forEach(n=>n.classList.toggle('active',n.dataset.tab===name));if(name==='studio')requestAnimationFrame(()=>viewer?.resize());}
document.querySelectorAll('nav [data-tab]').forEach(n=>n.onclick=()=>tab(n.dataset.tab));
function request(){const controls={radialSigma:Number($('radialSigma').value)};for(const k of modelKeys[$('generator').value])controls[k]=Number(values[k]??descriptors[k][4]);return {scene:$('scene').value,generator:$('generator').value,seed:Number($('seed').value),pose:['auto','random'].includes($('pose').value)?$('pose').value:Number($('pose').value),mode:$('mode').value,time:Number($('frame-time').value),fps:Number($('fps').value),edgeMixing:$('edge-mixing').checked,randomScene:$('random-scene').checked,controls};}
function estimates(){const model=catalog.generators.find(g=>g.id===$('generator').value),count=$('mode').value==='sequence'?10*Number($('fps').value)+1:1,sec=model.seconds*count;$('estimate').textContent=count+'프레임 · 계산 약 '+(sec<60?Math.ceil(sec)+'초':Math.ceil(sec/60)+'분')+' 전후. 장면·컴퓨터에 따라 달라집니다.';$('fps-label').hidden=$('mode').value!=='sequence';$('frame-time-label').hidden=$('mode').value==='sequence';}
function describeFrame(m){
 const source=m.sequencePlan?.dustSource,distance=source?Math.hypot(source.x-m.sensorPose.world[0],source.y-m.sensorPose.world[1]):0;
 $('observation-note').textContent=m.kind==='sun'?(m.stats.review?.clearSunPath===false?'이번 프레임은 태양 방향이 가려졌거나 태양이 수평선 아래에 있어 가짜 반환이 생기지 않습니다. 태양 방향·고도를 바꿔 비교하세요.':'태양 방향은 열려 있습니다. 확률적으로 선택된 반환을 표시하며 미지원 신호·반사도는 채우지 않습니다.'):m.kind==='dust'?'발생원까지 수평 거리 '+distance.toFixed(1)+'m. '+((m.stats.dust||0)===0?'현재 검출 먼지는 0개입니다. 발생원 확대와 운동 표본으로 위치를 확인하세요.':'발생원은 고정되고 방출 입자가 이동합니다. 관측점과 운동 표본은 다릅니다.'):job.request.generator==='edge'?'노란 불확실 표면 '+(m.stats.uncertain||0).toLocaleString()+'점. 삭제 정답이 아닙니다.':'';
}
function stopPlayback(){playing=false;clearTimeout(playTimer);$('play').textContent='재생';}
function poseCaption(){const p=$('pose').value;return p==='random'?'연속 랜덤 시작':p==='auto'?'40곳 중 자동 선택':'시작점 '+(Number(p)+1);}
function invalidate(){if(job?.status==='running')return;seekTicket++;stopPlayback();viewer?.clearObservation();frameCache.clear();job=null;selection=0;previewKey='';$('job-progress').hidden=true;$('timeline').disabled=true;for(const k of ['previous-frame','play','next-frame'])$(k).disabled=true;$('download-frame').hidden=$('download-manifest').hidden=true;$('time-label').textContent='생성된 프레임 없음';$('observation-note').textContent='';$('pose-info').textContent='생성 후 센서의 yaw·pitch·roll을 표시합니다.';$('fit-source').hidden=true;$('viewer-caption').textContent='환경 형상 미리보기 · 이 조건의 관측을 생성하세요.';$('metrics').querySelectorAll('b').forEach(n=>n.textContent='—');$('frame-info').textContent='조건이 바뀌었습니다. 생성하면 적용 설정과 해시를 표시합니다.';status('조건이 바뀌었습니다. 실제 관측 생성을 눌러 확인하세요.');}
function busy(on){$('generation-form').querySelectorAll('input,select,button').forEach(n=>n.disabled=on);$('cancel').disabled=false;$('cancel').hidden=!on;$('load-settings').disabled=on;document.querySelectorAll('.scene-card button,.generator-card button').forEach(n=>n.disabled=on);}
function modelUI(){const name=$('generator').value,model=catalog.generators.find(g=>g.id===name);$('model-hint').textContent=model.description;const container=$('model-controls');container.replaceChildren();for(const k of modelKeys[name]){const [title,min,max,step,def,unit]=descriptors[k];const label=el('label',title+' '),input=el('input'),output=el('output');input.type='range';input.id=k;input.min=min;input.max=max;input.step=step;input.value=values[k]??def;output.htmlFor=k;output.textContent=input.value+unit;input.oninput=()=>{values[k]=Number(input.value);output.textContent=input.value+unit;invalidate();};label.append(input,output);container.append(label);}if(!modelKeys[name].length)container.append(el('p',name==='edge'?'13개 부광선으로 표면 경계를 계산합니다.':'아래 공통 거리 오차를 조절하세요.','small'));estimates();}
async function changeScene(){const ticket=++sceneTicket;sceneLoading=true;invalidate();$('generate').disabled=true;row=catalog.scenes.find(s=>s.id===$('scene').value);$('scene-title').textContent=row.title+' · 배치 '+row.variant;$('scene-subtitle').textContent=row.id+' · '+poseCaption()+' · 6DoF';for(const option of $('generator').options){const g=catalog.generators.find(g=>g.id===option.value);option.disabled=!!g.outdoorOnly&&D.indoor(row);}if($('generator').selectedOptions[0].disabled)$('generator').value='range';modelUI();$('cutaway').checked=D.indoor(row);$('viewer-caption').textContent='실제 장소 형상 읽는 중…';try{await viewer.setScene(row);}finally{if(ticket===sceneTicket){sceneLoading=false;$('generate').disabled=job?.status==='running';}}if(ticket!==sceneTicket)return;$('viewer-caption').textContent='실제 메시 · '+row.title+' · 배치 '+row.variant+' · 관측 생성 전';}
function updateDisplay(){$('viewer-legend').textContent=$('point-color').value==='reflectivity'?'반사도 추정값: 파랑(낮음) → 빨강(높음) · 회색 미지원':$('point-color').value==='labels'?'청록 표면 · 주황 산란·가짜 반환 · 노랑 불확실 표면':'관측점 단색 표시';$('reflectivity').checked=$('point-color').value==='reflectivity';$('fit-source').hidden=!viewer.emitter||viewer.frame?.metadata.kind!=='dust';viewer.setOptions({display:$('display').value,color:$('point-color').value,cutaway:$('cutaway').checked,path:$('show-path').checked,poses:$('show-poses').checked,particles:$('show-particles').checked,noise:$('noise-only').checked,size:Number($('point-size').value)});$('display-note').textContent=$('point-color').value==='reflectivity'?'반사도는 미교정 추정값입니다. 햇빛 등 미지원 채널은 회색으로 표시합니다.':$('show-particles').checked?'주황 운동 표본은 실제 관측과 별개인 물리 후보입니다. 라벨 수나 저장 관측점을 늘리지 않습니다.':'메시의 색은 보기 위한 색이며 실제 반사도 값이 아닙니다. 녹색 선은 실제 센서 경로, 흰 화살표는 현재 방향입니다.';}
async function seek(index){if(!job||!job.frames[index])return;const ticket=++seekTicket,id=job.id,f=job.frames[index];selection=index;$('timeline').value=index;$('time-label').textContent=f.time.toFixed(1)+' / 10초 · 읽는 중';let frame=frameCache.get(f.index);if(!frame){frame=await D.readFrame(f.url);if(ticket!==seekTicket||job?.id!==id)return;frameCache.set(f.index,frame);if(frameCache.size>3)frameCache.delete(frameCache.keys().next().value);}if(ticket!==seekTicket||job?.id!==id)return;viewer.setFrame(frame);const m=frame.metadata;describeFrame(m);$('pose-info').textContent='몸체 yaw / pitch / roll: '+[m.sensorPose.yawDeg,m.sensorPose.pitchDeg||0,m.sensorPose.rollDeg||0].map(v=>v.toFixed(1)+'°').join(' / ')+' · 추가 소품 '+(m.sceneLayout?.instances.length||0)+'개';$('viewer-caption').textContent='실제 저장 관측 · '+catalog.generators.find(g=>g.id===job.request.generator).name+' · '+m.time.toFixed(1)+'초 · 좌표·라벨 해시 확인';$('time-label').textContent=m.time.toFixed(1)+' / 10초 · '+(index+1)+'/'+job.frames.length;const metrics=$('metrics').querySelectorAll('b');metrics[0].textContent=m.points.toLocaleString();metrics[1].textContent=(m.stats.dust||0).toLocaleString();metrics[2].textContent=m.time.toFixed(1)+'초';metrics[3].textContent=m.sensorPose.world.map(v=>v.toFixed(2)).join(', ')+' m';$('frame-info').textContent=JSON.stringify({scene:m.scene,seed:m.seed,generator:job.request.generator,time:m.time,geometry:m.geometry,sceneLayout:m.sceneLayout,sensorPose:m.sensorPose,route:m.sequencePlan?.waypoints,source:m.sequencePlan?.dustSource,xyz_labels_sha256:m.xyz_labels_sha256,channels:m.channels,stats:m.stats,field_calibrated:false,training_approved:false},null,2);$('download-frame').href=f.url;$('download-frame').hidden=false;updateDisplay();}

async function playback(){if(!playing||!job)return;if(selection>=job.frames.length-1){stopPlayback();return;}const delay=Math.max(50,(job.frames[selection+1].time-job.frames[selection].time)*1000);playTimer=setTimeout(async()=>{if(!playing)return;try{await seek(selection+1);playback();}catch(e){stopPlayback();fail(e);}},delay);}
function updateJob(j){job=j;const n=j.frames.length,running=j.status==='running';$('job-progress').hidden=!running;let p=j.progress?.progress||0;if(p>1)p/=100;$('job-progress').value=Math.min(1,(n+Math.max(0,Math.min(.95,p)))/j.total);const elapsed=Math.round(j.elapsedS);status(running?'계산 중 · '+n+'/'+j.total+'프레임 · 현재 '+(j.currentTime??0)+'초 · '+elapsed+'초 경과':j.status==='complete'?'생성 완료 · '+n+'프레임 · '+elapsed+'초 · 좌표를 바꾸지 않고 파일에서 표시합니다.':j.status==='cancelled'?'생성을 중지했습니다. 완료한 '+n+'프레임은 보존됩니다.':'생성 오류: '+j.error,j.status==='error');if(viewer.frame)$('time-label').textContent=viewer.frame.metadata.time.toFixed(1)+' / 10초 · '+(selection+1)+'/'+n;$('timeline').max=Math.max(0,n-1);$('timeline').disabled=!n;for(const k of ['previous-frame','next-frame'])$(k).disabled=n<2;$('play').disabled=n<2;$('download-manifest').hidden=!j.manifestUrl;if(j.manifestUrl)$('download-manifest').href=j.manifestUrl;busy(running);if(j.preview){const key=j.id+':'+(j.preview.sensorPose?.time??'path');if(!previewKey){viewer.setPreview(j.preview);viewer.fitRoute();}previewKey=key;}if(n&&!viewer.frame)void seek(0).catch(fail);if(!running)clearTimeout(pollTimer);}
async function poll(id){try{const j=await api('/api/jobs/'+id);if(job?.id!==id)return;updateJob(j);if(j.status==='running')pollTimer=setTimeout(()=>poll(id),650);}catch(e){busy(false);fail(e);}}
async function generate(e){e?.preventDefault();if(sceneLoading||job?.status==='running')return;invalidate();busy(true);status('실제 시뮬레이터 시작 중…');try{const j=await api('/api/jobs',request());job=j;sessionStorage.setItem('review-job',j.id);updateJob(j);void poll(j.id);}catch(e){busy(false);fail(e);}}
function downloadJSON(name,data){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),a=el('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function applySettings(s){if(!catalog.scenes.some(r=>r.id===s.scene)||!catalog.generators.some(g=>g.id===s.generator)||!Number.isInteger(s.seed)||s.seed<0||s.seed>4294967295||!['frame','sequence'].includes(s.mode)||!Number.isFinite(s.time)||s.time<0||s.time>10||![1,2,5,10].includes(s.fps)||(!['auto','random'].includes(s.pose)&&(!Number.isInteger(s.pose)||s.pose<0||s.pose>39)))throw Error('지원하지 않는 설정입니다.');const target=catalog.scenes.find(r=>r.id===s.scene),model=catalog.generators.find(g=>g.id===s.generator);if(model.outdoorOnly&&D.indoor(target))throw Error('비·눈은 야외 장소에서 사용하세요.');for(const [k,v]of Object.entries(s.controls||{})){const rule=k==='radialSigma'?['',0,.15]:descriptors[k];if(!rule||typeof v!=='number'||!Number.isFinite(v)||v<rule[1]||v>rule[2])throw Error('설정 범위 오류: '+k);}invalidate();$('scene').value=s.scene;$('generator').value=s.generator;$('seed').value=s.seed;$('pose').value=s.pose;$('mode').value=s.mode;$('frame-time').value=s.time;$('fps').value=s.fps;$('edge-mixing').checked=s.edgeMixing===true;$('random-scene').checked=s.randomScene!==false;for(const k of Object.keys(values))delete values[k];Object.assign(values,s.controls||{});$('radialSigma').value=values.radialSigma??.06;document.querySelector('output[for=radialSigma]').textContent=(Number($('radialSigma').value)*100).toFixed(1)+'cm';await changeScene();modelUI();tab('studio');}
try{
 catalog=await api('/api/catalog');viewer=new D.ReviewViewer($('viewer'));for(const s of catalog.scenes){const option=el('option',s.title+' · 배치 '+s.variant);option.value=s.id;$('scene').append(option);}for(const g of catalog.generators){const option=el('option',g.name);option.value=g.id;$('generator').append(option);}for(let i=0;i<40;i++){const option=el('option','시작점 '+(i+1));option.value=i;$('pose').append(option);}$('scene').value='construction_v1';$('generator').value='dust';
 for(const [family,description]of Object.entries(catalog.families)){const name=catalog.scenes.find(s=>s.family===family)?.title||family,opt=el('option',name);opt.value=family;$('family-filter').append(opt);}
 const images=new Map();for(const s of catalog.scenes){const card=el('article',undefined,'scene-card');card.dataset.scene=s.id;card.dataset.family=s.family;const img=el('img');img.alt=s.title+' 배치 '+s.variant+' 실제 형상';img.width=510;img.height=300;images.set(s.id,img);const body=el('div',undefined,'card-body');body.append(el('div',s.id+' / RANDOM + 40 STARTS','card-kicker'),el('h3',s.title+' · 배치 '+s.variant),el('p',catalog.families[s.family],'small'),el('div',s.inventory.join(' · '),'inventory'));const b=el('button','이 장소 열기 →');b.onclick=()=>{if(job?.status==='running')return;$('scene').value=s.id;tab('studio');void changeScene().catch(fail);};body.append(b);card.append(img,body);$('scene-grid').append(card);}
 $('family-filter').onchange=()=>document.querySelectorAll('.scene-card').forEach(n=>n.hidden=$('family-filter').value!=='all'&&n.dataset.family!==$('family-filter').value);
 for(const g of catalog.generators){const card=el('article',undefined,'generator-card');card.dataset.generator=g.id;card.append(el('div',g.tag,'tag'),el('h3',g.name),el('p',g.description),el('p',g.look,'small'),el('p',g.limit,'limit'));const b=el('button','이 생성기로 확인 →');b.onclick=()=>{if(job?.status==='running')return;invalidate();$('generator').value=g.id;if(g.outdoorOnly&&D.indoor(row)){$('scene').value='construction_v1';void changeScene().catch(fail);}else modelUI();tab('studio');};card.append(b);$('generator-grid').append(card);}for(const d of catalog.deferred){const p=el('p');p.append(el('strong',d.name+' · '),document.createTextNode(d.reason));$('deferred-list').append(p);}
 $('generation-form').onsubmit=generate;$('scene').onchange=()=>void changeScene().catch(fail);$('generator').onchange=()=>{invalidate();modelUI();};for(const k of ['seed','pose','mode','fps','frame-time','edge-mixing','random-scene'])$(k).onchange=()=>{invalidate();estimates();$('scene-subtitle').textContent=row.id+' · '+poseCaption()+' · 6DoF';};$('random-seed').onclick=()=>{$('seed').value=crypto.getRandomValues(new Uint32Array(1))[0];invalidate();};$('radialSigma').oninput=()=>{document.querySelector('output[for=radialSigma]').textContent=(Number($('radialSigma').value)*100).toFixed(1)+'cm';invalidate();};for(const k of ['display','point-color','cutaway','show-path','show-poses','show-particles','noise-only','point-size'])$(k).oninput=updateDisplay;$('reflectivity').oninput=()=>{$('point-color').value=$('reflectivity').checked?'reflectivity':'labels';updateDisplay();};$('fit-scene').onclick=()=>viewer.fitScene();$('fit-route').onclick=()=>viewer.fitRoute();$('top-view').onclick=()=>viewer.top();$('fit-source').onclick=()=>viewer.fitSource();
 $('cancel').onclick=async()=>{if(!job)return;$('cancel').disabled=true;try{await api('/api/jobs/'+job.id+'/cancel',{});await poll(job.id);}catch(e){fail(e);}};$('timeline').oninput=()=>{stopPlayback();void seek(Number($('timeline').value)).catch(fail);};$('previous-frame').onclick=()=>{stopPlayback();void seek(Math.max(0,selection-1)).catch(fail);};$('next-frame').onclick=()=>{stopPlayback();void seek(Math.min(job.frames.length-1,selection+1)).catch(fail);};$('play').onclick=async()=>{if(playing)return stopPlayback();try{if(selection===job.frames.length-1)await seek(0);playing=true;$('play').textContent='일시정지';playback();}catch(e){fail(e);}};
 $('save-settings').onclick=()=>downloadJSON('lidar-review-settings.json',{schema:1,...request()});$('load-settings').onchange=async()=>{try{const file=$('load-settings').files[0];if(!file)return;if(file.size>65536)throw Error('설정 파일이 너무 큽니다.');await applySettings(JSON.parse(await file.text()));status('설정을 불러왔습니다. 실제 관측 생성을 눌러 재현하세요.');}catch(e){fail(e);}finally{$('load-settings').value='';}};
 await changeScene();updateDisplay();let count=0;void D.thumbnails(catalog.scenes,(s,url)=>{const img=images.get(s.id);img.src=url;img.dataset.geometry=s.geometry.id;img.dataset.sha256=s.geometry.sha256;$('catalog-status').textContent='실제 메시 미리보기 '+(++count)+' / 24';},(s,e)=>{images.get(s.id).alt=s.title+' 형상 오류: '+e.message;}).catch(e=>{$('catalog-status').textContent='미리보기 오류: '+e.message;});
 const recent=sessionStorage.getItem('review-job'),last=catalog.active||(catalog.knownJobs?.includes(recent)?recent:null);if(last){try{const saved=await api('/api/jobs/'+last);await applySettings(saved.request);updateJob(saved);if(saved.status==='running')void poll(last);}catch(e){sessionStorage.removeItem('review-job');}}
}catch(e){$('fatal').hidden=false;$('fatal').textContent='검토실을 시작하지 못했습니다: '+e.message+' · 저장소에서 python tools/build.py 후 node tools/review-server.cjs를 실행하고 http://127.0.0.1:18769/ 를 여세요.';}
})();
